import { type ContentPost } from "./content-types";

export const EVENING_POSTS: ContentPost[] = [
  // === SEMANA 1: NOITE — EMOCIONAL (a mãe sente-se vista) ===
  {
    day: 1, slot: "evening", time: "13:00", type: "video", categoria: "espelho",
    title: "O que ninguém te diz",
    slides: [
      { layout: "kinetic-line", body: "Ninguém te diz isto sobre ser mãe:" },
      { layout: "kinetic-line", body: "Que vais gritar e depois chorar escondida." },
      { layout: "kinetic-line", body: "Que vais sentir culpa todos os dias." },
      { layout: "kinetic-line", body: "Que vais desaparecer aos poucos." },
      { layout: "kinetic-line", body: "Que vais sorrir quando te perguntarem como estás." },
      { layout: "kinetic-line", body: "E que ninguém vai perguntar a sério." },
      { layout: "kinetic-line", body: "Tu não estás a falhar.\nEstás a carregar peso a mais." },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe.\nDiagnóstico grátis na bio." },
    ],
    caption: "Ninguém te prepara para o peso invisível de ser mãe.\n\nE quando pedes ajuda, dizem-te que \"faz parte\".\n\nNão faz. Não tem de ser assim.\n\nGuarda e envia a uma mãe que precisa de ler isto.",
    hashtags: "#FreeMe #MãeReal #MaternidadeReal #CulpaMaterna #NinguémTeDiz #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 2, slot: "evening", time: "13:00", type: "carousel", categoria: "ferida",
    title: "A mãe que sorri",
    slides: [
      { layout: "capa", body: "Ela sorri.\nPor dentro está a desabar.", bold: ["sorri", "desabar"] },
      { layout: "conteudo", body: "Diz que está bem.\nResolve tudo.\nNão pede ajuda." },
      { layout: "conteudo", body: "Porque a mãe não se pode queixar.\nA mãe aguenta." },
      { layout: "conteudo", body: "E ninguém vê que por dentro a mãe desapareceu.", bold: ["desapareceu"] },
      { layout: "citacao", body: "Tu não desapareceste. Ficaste debaixo de tudo o que carregas." },
      { layout: "cta", body: "Diagnóstico grátis.\nfreeme.viviannedossantos.com" },
    ],
    caption: "Ela sorri. Por dentro está a desabar.\n\nSe és essa mãe, eu vejo-te.\n\nGuarda e envia a quem precisa.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãeInvisível #MãeSemCulpa #MaternidadeReal #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 3, slot: "evening", time: "13:00", type: "video", categoria: "espelho",
    title: "5 sinais de sobrecarga",
    slides: [
      { layout: "kinetic-line", body: "5 sinais de que carregas peso que não é teu:" },
      { layout: "kinetic-line", body: "1. Sentes que se parares, tudo desaba." },
      { layout: "kinetic-line", body: "2. Dizes que estás bem quando não estás." },
      { layout: "kinetic-line", body: "3. Resolves os problemas de toda a gente menos os teus." },
      { layout: "kinetic-line", body: "4. Compensas o que achas que falhaste." },
      { layout: "kinetic-line", body: "5. Não te lembras da última vez que fizeste algo só para ti." },
      { layout: "kinetic-line", body: "Se te reconheceste em 3 ou mais, não é cansaço.\nÉ sobrecarga sistémica.", bold: ["sobrecarga sistémica"] },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Se te reconheceste em 3 ou mais, não é cansaço normal. É um padrão.\n\nE tem nome. E tem saída.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #Sobrecarga #MãeEsgotada #Sinais #MaternidadeReal #CargaMental #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 4, slot: "evening", time: "13:00", type: "carousel", categoria: "ferida",
    title: "O que carregas",
    slides: [
      { layout: "capa", body: "O teu filho.\nOs problemas do pai dele.\nA tristeza dos teus pais.\nOs conflitos da família toda.", bold: ["família toda"] },
      { layout: "conteudo", body: "Tudo. Nos teus ombros.\n\nE a sensação de que se largares um bocadinho, desaba." },
      { layout: "conteudo", body: "Mas e se largasses o que não é teu?", bold: ["o que não é teu"] },
      { layout: "citacao", body: "Ficas mais leve não porque deixaste de amar. Ficas mais leve porque pousaste o que nunca foi teu." },
      { layout: "cta", body: "Diagnóstico grátis.\nfreeme.viviannedossantos.com" },
    ],
    caption: "Repara no que sustentas. O teu filho, claro. Mas só o teu filho?\n\nTu tornaste-te a que aguenta tudo.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #OPeso #CargaMental #MãeSemCulpa #ConstelacaoFamiliar #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 5, slot: "evening", time: "13:00", type: "video", categoria: "voz",
    title: "Amor não é sacrifício",
    slides: [
      { layout: "kinetic-line", body: "Amar não exige desapareceres." },
      { layout: "kinetic-line", body: "Cuidar não exige anulares-te." },
      { layout: "kinetic-line", body: "Servir não exige abandonares-te." },
      { layout: "kinetic-line", body: "Se o teu amor te está a apagar," },
      { layout: "kinetic-line", body: "não é amor a mais." },
      { layout: "kinetic-line", body: "É peso a mais.", bold: ["peso a mais"] },
      { layout: "kinetic-line", body: "Dá para amar inteira.\nAliás, só assim é que dá para amar por muito tempo." },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe." },
    ],
    caption: "Se o teu amor te está a apagar, não é amor a mais. É peso a mais.\n\nGuarda e envia a uma mãe que precisa.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #AmorNãoÉSacrifício #MãeInteira #ConstelacaoFamiliar #MaternidadeReal",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 6, slot: "evening", time: "13:00", type: "carousel", categoria: "espelho",
    title: "Antes de seres mãe",
    slides: [
      { layout: "capa", body: "Antes de seres mãe,\neras uma mulher.\n\nLembras-te dela?", bold: ["Lembras-te dela?"] },
      { layout: "conteudo", body: "Tinha vontades.\nTinha um nome que não era só \"mãe\".\nTinha tempo.\nTinha energia para si." },
      { layout: "conteudo", body: "Não desapareceu.\nFicou debaixo de tudo o que carregas." },
      { layout: "citacao", body: "Também pertenço à minha vida. Também sou alguém que precisa de ser cuidada." },
      { layout: "cta", body: "Diagnóstico grátis.\nfreeme.viviannedossantos.com" },
    ],
    caption: "Tu não desapareceste. Ficaste debaixo de tudo o que carregas.\n\nPodes voltar a ti sem deixar de ser mãe.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #VoltarAMim #MãeEMulher #MaternidadeReal #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 7, slot: "evening", time: "13:00", type: "carousel", categoria: "cta",
    title: "7 perguntas, 2 minutos",
    slides: [
      { layout: "capa", body: "7 perguntas.\n2 minutos.\nE vais perceber porque carregas o que carregas.", bold: ["7 perguntas", "2 minutos"] },
      { layout: "conteudo", body: "Não é um quiz.\nNão é um teste de personalidade.\n\nÉ um espelho." },
      { layout: "conteudo", body: "O FreeMe calcula, em silêncio, qual dos 7 bloqueios emocionais mais te prende.", bold: ["em silêncio"] },
      { layout: "conteudo", body: "Peso. Vazio. Culpa. Medo.\nVergonha. Mágoa. Rancor.\n\nCada um com uma travessia." },
      { layout: "cta", body: "Diagnóstico grátis.\nSem compromisso.\n\nfreeme.viviannedossantos.com" },
    ],
    caption: "7 perguntas. 2 minutos. E vais perceber porque carregas o que carregas.\n\nDiagnóstico grátis. freeme.viviannedossantos.com\n\nGuarda este post.",
    hashtags: "#FreeMe #DiagnósticoGrátis #7Bloqueios #ConstelacaoFamiliar #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  // === SEMANA 2: NOITE — EMOCIONAL (bloqueios pessoais) ===
  {
    day: 8, slot: "evening", time: "13:00", type: "video", categoria: "espelho",
    title: "A mãe que não educa",
    slides: [
      { layout: "kinetic-line", body: "Cedes quando devias dizer não." },
      { layout: "kinetic-line", body: "Compensas com prendas e atenção extra." },
      { layout: "kinetic-line", body: "Pedes desculpa por existir." },
      { layout: "kinetic-line", body: "Não pões limites porque te sentes em dívida." },
      { layout: "kinetic-line", body: "Isto não é amor.\nÉ culpa a comandar.", bold: ["culpa a comandar"] },
      { layout: "kinetic-line", body: "A culpa não te torna melhor mãe.\nTorna-te uma mãe que não educa." },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "A culpa não te torna melhor mãe. Torna-te uma mãe que não educa.\n\nGuarda e envia a uma mãe que precisa.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #CulpaMaterna #Limites #Educação #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 9, slot: "evening", time: "13:00", type: "carousel", categoria: "ferida",
    title: "Ninguém te pergunta",
    slides: [
      { layout: "capa", body: "\"Como estás?\"\n\nNinguém te pergunta.\nE quando perguntam,\ntu dizes \"bem\".", bold: ["\"bem\""] },
      { layout: "conteudo", body: "Porque a mãe resolve.\nA mãe cuida.\nA mãe sorri." },
      { layout: "conteudo", body: "E por dentro, a mãe desaparece.", bold: ["desaparece"] },
      { layout: "citacao", body: "O vazio não é falta de amor. É interrupção do fluxo. Dás muito, recebes pouco, e a conta não fecha." },
      { layout: "cta", body: "Diagnóstico grátis.\nfreeme.viviannedossantos.com" },
    ],
    caption: "Tu cuidas de todos. E quem cuida de ti?\n\nSe a resposta é \"ninguém\", o vazio não é um mistério. É matemática.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #OVazio #MãeEsgotada #MaternidadeReal #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 10, slot: "evening", time: "13:00", type: "video", categoria: "espelho",
    title: "A mãe perfeita",
    slides: [
      { layout: "kinetic-line", body: "Ela nunca perde a paciência." },
      { layout: "kinetic-line", body: "Está sempre disponível." },
      { layout: "kinetic-line", body: "Dá conta de tudo, sozinha, a sorrir." },
      { layout: "kinetic-line", body: "Conheces esta mãe?" },
      { layout: "kinetic-line", body: "Ela não existe.", bold: ["não existe"] },
      { layout: "kinetic-line", body: "Nunca existiu." },
      { layout: "kinetic-line", body: "E quanto mais a tentas ser,\nmaior a vergonha de não conseguir." },
      { layout: "kinetic-line", body: "Pertenço exactamente como sou." },
    ],
    caption: "A mãe perfeita é a maior mentira que te contaram.\n\nGuarda e partilha.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãePerfeita #MãeImperfeita #AVergonha #MaternidadeReal #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 11, slot: "evening", time: "13:00", type: "carousel", categoria: "ferida",
    title: "A ferida de filha",
    slides: [
      { layout: "capa", body: "Antes de seres mãe,\nfoste filha.\n\nE talvez aí algo\nte tenha faltado.", bold: ["faltado"] },
      { layout: "conteudo", body: "Presença. Colo. Proteção.\nSer vista. Ser escolhida." },
      { layout: "conteudo", body: "A mágoa tem o olhar voltado para trás.\nUma parte de ti ficou ali, à espera.", bold: ["à espera"] },
      { layout: "citacao", body: "Tens direito a esse luto. O luto da mãe que precisavas e não tiveste." },
      { layout: "cta", body: "Diagnóstico grátis.\nfreeme.viviannedossantos.com" },
    ],
    caption: "A mágoa esconde muitas vezes um luto que nunca se chorou.\n\nGuarda este post.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #AMágoa #FeridaDeFilha #MãeEFilha #ConstelacaoFamiliar #CuraInterior",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 12, slot: "evening", time: "13:00", type: "video", categoria: "voz",
    title: "O rancor protege",
    slides: [
      { layout: "kinetic-line", body: "O rancor não é um defeito de caráter." },
      { layout: "kinetic-line", body: "É uma ferida que ainda não foi reconhecida." },
      { layout: "kinetic-line", body: "Por baixo da raiva há quase sempre" },
      { layout: "kinetic-line", body: "uma dor que ninguém viu." },
      { layout: "kinetic-line", body: "Enquanto estás zangada,\nnão tens de tocar na parte que dói mesmo." },
      { layout: "kinetic-line", body: "O rancor é a casca dura\nsobre a ferida.", bold: ["casca dura"] },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "O rancor não é mau caráter. É uma ferida que ainda não foi reconhecida.\n\nGuarda e partilha.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #ORancor #Raiva #CuraInterior #ConstelacaoFamiliar #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 13, slot: "evening", time: "13:00", type: "carousel", categoria: "espelho",
    title: "A mãe que desapareceu",
    slides: [
      { layout: "capa", body: "Ela tinha um nome\nantes de ser mãe.\n\nTinha vontades.\nTinha vida.", bold: ["vida"] },
      { layout: "conteudo", body: "Não desapareceu.\nFicou debaixo de tudo o que carrega." },
      { layout: "conteudo", body: "E todos os dias acorda, sorri, resolve, aguenta.\nE ninguém vê." },
      { layout: "conteudo", body: "Eu vejo.", bold: ["Eu vejo."] },
      { layout: "cta", body: "FreeMe. A Travessia da Mãe.\nDiagnóstico grátis na bio." },
    ],
    caption: "Se és essa mãe, eu vejo-te.\n\nPodes voltar a ti sem deixar de ser mãe.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãeInvisível #VoltarAMim #MaternidadeReal #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 14, slot: "evening", time: "13:00", type: "carousel", categoria: "cta",
    title: "Os 7 bloqueios resumo",
    slides: [
      { layout: "capa", body: "Os 7 bloqueios emocionais\nque prendem as mães.\n\nQual é o teu?", bold: ["Qual é o teu?"] },
      { layout: "conteudo", body: "Peso. Vazio. Culpa.\nMedo. Vergonha.\nMágoa. Rancor." },
      { layout: "conteudo", body: "Não tens de os atravessar todos.\nSó os que te prendem." },
      { layout: "conteudo", body: "O FreeMe mostra-te quais são\ne monta um percurso adaptado a ti.", bold: ["adaptado a ti"] },
      { layout: "cta", body: "7 perguntas. 2 minutos. Grátis.\n\nfreeme.viviannedossantos.com" },
    ],
    caption: "Peso, vazio, culpa, medo, vergonha, mágoa, rancor.\n\nNão tens de os atravessar todos. Só os que te prendem.\n\nGuarda este post.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #7Bloqueios #ConstelacaoFamiliar #CulpaMaterna #MãeSemCulpa #DiagnósticoGrátis",
    platforms: ["ig", "tiktok"],
  },

  // === SEMANA 3: NOITE — EMOCIONAL (transformação) ===
  {
    day: 15, slot: "evening", time: "13:00", type: "video", categoria: "movimento",
    title: "Honrar sem repetir",
    slides: [
      { layout: "kinetic-line", body: "Uma voz que passou de mulher para mulher:" },
      { layout: "kinetic-line", body: "\"Uma boa mãe aguenta tudo.\"" },
      { layout: "kinetic-line", body: "\"Primeiro os outros, eu por último.\"" },
      { layout: "kinetic-line", body: "Talvez a tua avó tenha vivido assim.\nTalvez a tua mãe." },
      { layout: "kinetic-line", body: "E tu, sem decidir, continuaste." },
      { layout: "kinetic-line", body: "Mas podes honrar o sacrifício delas\nsem o repetir.", bold: ["sem o repetir"] },
      { layout: "kinetic-line", body: "\"Honro o vosso caminho.\nNão preciso de o repetir.\nEscolho viver a minha própria vida.\"" },
    ],
    caption: "Não tens de sofrer como elas sofreram para lhes pertencer.\n\nEsse preço não é amor. É peso.\n\nGuarda e envia a uma mãe que precisa.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #HonrarSemRepetir #Linhagem #Ancestralidade #ConstelacaoFamiliar #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 16, slot: "evening", time: "13:00", type: "carousel", categoria: "espelho",
    title: "10 coisas que mães nunca dizem",
    slides: [
      { layout: "capa", body: "10 coisas que quase todas\nas mães sentem\ne nunca dizem a ninguém.", bold: ["nunca dizem"] },
      { layout: "conteudo", body: "1. Às vezes queria fugir 5 minutos.\n2. Tenho inveja de quem parece fazer tudo bem.\n3. Gritei e depois chorei escondida." },
      { layout: "conteudo", body: "4. Sinto que não sou suficiente.\n5. Não sei quem sou sem eles.\n6. Tenho raiva de quem me deixou sozinha." },
      { layout: "conteudo", body: "7. Carrego uma culpa que não sei nomear.\n8. Tenho medo de repetir a minha mãe.\n9. Preciso de ajuda e não sei pedir." },
      { layout: "conteudo", body: "10. Merecia que alguém cuidasse de mim.", bold: ["cuidasse de mim"] },
      { layout: "cta", body: "Se te reconheceste em 3, não estás sozinha.\n\nDiagnóstico grátis na bio." },
    ],
    caption: "Se te reconheceste em pelo menos 3, não estás sozinha. Estás num padrão.\n\nE tem saída.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãeReal #10Coisas #MaternidadeReal #CulpaMaterna #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 17, slot: "evening", time: "13:00", type: "video", categoria: "movimento",
    title: "Ocupar o teu lugar",
    slides: [
      { layout: "kinetic-line", body: "Tu não és a salvadora do teu filho." },
      { layout: "kinetic-line", body: "Não és a juíza." },
      { layout: "kinetic-line", body: "Tu és a mãe." },
      { layout: "kinetic-line", body: "Só isso." },
      { layout: "kinetic-line", body: "E é tudo.", bold: ["E é tudo."] },
      { layout: "kinetic-line", body: "\"Eu sou a mãe. Tu és o filho.\nTomei-te da melhor forma que pude.\nO resto pertence à tua vida.\"" },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Ocupar o teu lugar não é abandonar. É o contrário.\n\nSó no teu lugar é que podes realmente ser mãe.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #OTeuLugar #OrdensDoAmor #ConstelacaoFamiliar #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 18, slot: "evening", time: "13:00", type: "carousel", categoria: "voz",
    title: "Quem é a Vivianne",
    slides: [
      { layout: "capa", body: "Sou a Vivianne.\nEscritora. Mãe de três.", bold: ["Mãe de três"] },
      { layout: "conteudo", body: "Em formação em constelação familiar sistémica.\nA abordagem que sustenta esta travessia." },
      { layout: "conteudo", body: "Criei o FreeMe porque conheço esta culpa por dentro." },
      { layout: "citacao", body: "Ninguém merece carregá-la sozinha, no escuro, sem direito a queixa." },
      { layout: "cta", body: "FreeMe. A Travessia da Mãe.\nfreeme.viviannedossantos.com" },
    ],
    caption: "Criei o FreeMe porque nenhuma mãe deveria carregar a culpa sozinha.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #VivianneDDosSantos #ConstelacaoFamiliar #ATravessiaDaMãe #Maternidade",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 19, slot: "evening", time: "13:00", type: "video", categoria: "espelho",
    title: "Mereces",
    slides: [
      { layout: "kinetic-line", body: "Mereces descanso sem culpa." },
      { layout: "kinetic-line", body: "Mereces pedir ajuda sem vergonha." },
      { layout: "kinetic-line", body: "Mereces um limite sem pedir desculpa." },
      { layout: "kinetic-line", body: "Mereces um tempo só teu." },
      { layout: "kinetic-line", body: "Mereces ocupar o teu lugar." },
      { layout: "kinetic-line", body: "E sempre mereceste.", bold: ["sempre mereceste"] },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Não precisas de merecer primeiro com mais sacrifício.\n\nJá mereces. Sempre mereceste.\n\nGuarda e envia a uma mãe que precisa.",
    hashtags: "#FreeMe #Mereces #Autocompaixão #MãeSemCulpa #MaternidadeReal #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 20, slot: "evening", time: "13:00", type: "carousel", categoria: "ferida",
    title: "Às 3 da manhã",
    slides: [
      { layout: "capa", body: "São 3 da manhã.\nTudo dorme menos tu.", bold: ["3 da manhã"] },
      { layout: "conteudo", body: "E a tua cabeça vai para as coisas que podias ter feito melhor.\nPara a lista do que ainda falta.\nPara o medo do que pode correr mal." },
      { layout: "conteudo", body: "Esse peso tem nome.\nE pode ficar mais leve.", bold: ["pode ficar mais leve"] },
      { layout: "cta", body: "Esta é a primeira pergunta do diagnóstico FreeMe.\n\n7 perguntas. 2 minutos. Grátis.\n\nfreeme.viviannedossantos.com" },
    ],
    caption: "É noite. Tudo dorme menos tu. E a tua cabeça não para.\n\nDiagnóstico grátis na bio.\n\nGuarda e envia a uma mãe que precisa.",
    hashtags: "#FreeMe #3DaManhã #Insónia #CulpaMaterna #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 21, slot: "evening", time: "13:00", type: "carousel", categoria: "cta",
    title: "O que é o FreeMe",
    slides: [
      { layout: "capa", body: "Não é um curso.\nNão é conteúdo.\nNão é terapia.\n\nÉ uma travessia.", bold: ["travessia"] },
      { layout: "conteudo", body: "1. Diagnóstico grátis (7 perguntas)\n2. Vês o teu mapa\n3. Desbloqueias o percurso" },
      { layout: "conteudo", body: "Áudios guiados pela minha voz.\nExercícios de escrita.\nAnotações privadas.\nValidação final." },
      { layout: "conteudo", body: "Pagamento único. Acesso vitalício." },
      { layout: "cta", body: "Diagnóstico grátis. Hoje.\n\nfreeme.viviannedossantos.com" },
    ],
    caption: "O FreeMe não te vai ensinar a ser mãe.\n\nÉ uma travessia que fazes por dentro para pousares o que não era teu.\n\nDiagnóstico grátis. freeme.viviannedossantos.com",
    hashtags: "#FreeMe #ATravessiaDaMãe #App #7Bloqueios #DiagnósticoGrátis #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },

  // === SEMANA 4: NOITE — EMOCIONAL (conversão) ===
  {
    day: 22, slot: "evening", time: "13:00", type: "video", categoria: "voz",
    title: "A culpa não é boa conselheira",
    slides: [
      { layout: "kinetic-line", body: "A culpa não te torna melhor mãe." },
      { layout: "kinetic-line", body: "Torna-te uma mãe que não educa.", bold: ["não educa"] },
      { layout: "kinetic-line", body: "Quem se sente em dívida" },
      { layout: "kinetic-line", body: "cede para compensar," },
      { layout: "kinetic-line", body: "não põe limites," },
      { layout: "kinetic-line", body: "pede desculpa por existir." },
      { layout: "kinetic-line", body: "A culpa não é boa conselheira.", bold: ["não é boa conselheira"] },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "A culpa não é boa conselheira.\n\nGuarda e partilha.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #CulpaNãoÉBoaConselheira #CulpaMaterna #Limites #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 23, slot: "evening", time: "13:00", type: "carousel", categoria: "espelho",
    title: "Carta à mãe do início",
    slides: [
      { layout: "capa", body: "Se pudesses voltar atrás\ne falar à mãe que eras\nquando tudo começou,\no que lhe dirias?", bold: ["o que lhe dirias?"] },
      { layout: "citacao", body: "Não vais dar conta de tudo. E não precisas." },
      { layout: "citacao", body: "O teu filho não precisa de perfeição. Precisa de presença." },
      { layout: "citacao", body: "A culpa que sentes não é tua toda. Parte dela foi herdada." },
      { layout: "citacao", body: "A mãe que és já era suficiente. Sempre foi.", bold: ["já era suficiente"] },
      { layout: "cta", body: "Diagnóstico grátis.\nfreeme.viviannedossantos.com" },
    ],
    caption: "Se pudesses voltar atrás, o que dirias à mãe do início?\n\nGuarda e partilha.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #CartaÀMãe #MaternidadeReal #MãeSemCulpa #Autocompaixão #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 24, slot: "evening", time: "13:00", type: "video", categoria: "movimento",
    title: "Não tens de repetir",
    slides: [
      { layout: "kinetic-line", body: "Quanto mais juras\n\"nunca serei como ela\"," },
      { layout: "kinetic-line", body: "mais presa a ela ficas." },
      { layout: "kinetic-line", body: "Combater alguém\ntambém é uma forma de não a largar." },
      { layout: "kinetic-line", body: "A liberdade é poderes ser diferente\nsem precisares de a rejeitar.", bold: ["sem precisares de a rejeitar"] },
      { layout: "kinetic-line", body: "\"Tu és a minha mãe.\nEu sou tua filha.\nRecebo-te como és.\nE sigo o meu caminho.\"" },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Quanto mais rejeitas a tua mãe, mais presa lhe ficas.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãeEFilha #Repetição #ConstelacaoFamiliar #Linhagem #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 25, slot: "evening", time: "13:00", type: "carousel", categoria: "ferida",
    title: "A geração sanduíche",
    slides: [
      { layout: "capa", body: "Cuidas dos filhos.\nCuidas dos pais.\nCuidas do marido.\n\nE quem cuida de ti?", bold: ["quem cuida de ti?"] },
      { layout: "conteudo", body: "Na constelação familiar, isto é deslocamento.\nSaíste do teu lugar e ocupaste o de todos os outros.", bold: ["deslocamento"] },
      { layout: "conteudo", body: "Cada lugar que ocupas que não é teu drena-te.\nE os outros não ficam melhor por isso." },
      { layout: "citacao", body: "Devolver não é abandonar. É respeitar." },
      { layout: "cta", body: "Diagnóstico grátis.\nfreeme.viviannedossantos.com" },
    ],
    caption: "Geração sanduíche: cuidas de todos e ninguém cuida de ti.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #GeraçãoSanduíche #CargaMental #ConstelacaoFamiliar #MãeSemCulpa #Sobrecarga",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 26, slot: "evening", time: "13:00", type: "video", categoria: "espelho",
    title: "A mãe perfeita não existe v2",
    slides: [
      { layout: "kinetic-line", body: "Ela nunca grita." },
      { layout: "kinetic-line", body: "Ela tem paciência infinita." },
      { layout: "kinetic-line", body: "Ela faz tudo com amor." },
      { layout: "kinetic-line", body: "Ela não existe.", bold: ["não existe"] },
      { layout: "kinetic-line", body: "O que escondemos pesa o dobro." },
      { layout: "kinetic-line", body: "O que incluímos, podemos pousar." },
      { layout: "kinetic-line", body: "\"Posso pertencer exactamente como sou.\nFico, mesmo sem ser perfeita.\"" },
    ],
    caption: "O que escondemos pesa o dobro. O que incluímos, podemos pousar.\n\nGuarda e partilha.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãeImperfeita #AVergonha #MaternidadeReal #Autocompaixão #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 27, slot: "evening", time: "13:00", type: "carousel", categoria: "cta",
    title: "O que muda",
    slides: [
      { layout: "capa", body: "O FreeMe não promete\nque a dor não volta.\n\nPromete que sabes\no caminho de volta a ti.", bold: ["o caminho de volta a ti"] },
      { layout: "conteudo", body: "E esse caminho não se desaprende." },
      { layout: "conteudo", body: "7 bloqueios. A minha voz.\nAs tuas palavras a provarem a mudança." },
      { layout: "cta", body: "Diagnóstico grátis.\nPercurso por pagamento único.\n\nfreeme.viviannedossantos.com" },
    ],
    caption: "O FreeMe não cura. Ninguém fica curado.\n\nMas quando sabes o caminho de volta a ti, esse caminho não se desaprende.\n\nDiagnóstico grátis. freeme.viviannedossantos.com",
    hashtags: "#FreeMe #Transformação #ATravessiaDaMãe #ConstelacaoFamiliar #7Bloqueios #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 28, slot: "evening", time: "13:00", type: "video", categoria: "voz",
    title: "Eu vejo-te",
    slides: [
      { layout: "kinetic-line", body: "Se és a mãe que gritou e depois chorou escondida." },
      { layout: "kinetic-line", body: "Se és a que carrega tudo sozinha." },
      { layout: "kinetic-line", body: "Se és a que diz que está bem quando não está." },
      { layout: "kinetic-line", body: "Se és a que tem medo de repetir a mãe dela." },
      { layout: "kinetic-line", body: "Se és a que precisa de ajuda e não sabe pedir." },
      { layout: "kinetic-line", body: "Eu vejo-te.", bold: ["Eu vejo-te."] },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe.\nDiagnóstico grátis na bio." },
    ],
    caption: "Se és essa mãe, eu vejo-te.\n\nO FreeMe foi feito para ti.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #EuVejoTe #MãeReal #MaternidadeReal #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 29, slot: "evening", time: "13:00", type: "carousel", categoria: "cta",
    title: "Como funciona",
    slides: [
      { layout: "capa", body: "Como funciona o FreeMe.", bold: ["Como funciona"] },
      { layout: "conteudo", body: "1. Um espelho à entrada (grátis)\nRespondes a 7 perguntas.\nVês qual bloqueio te prende." },
      { layout: "conteudo", body: "2. Um percurso só teu\nÁudios guiados, exercícios,\nanotações privadas." },
      { layout: "conteudo", body: "3. O reencontro\nA app mostra-te, pelas tuas palavras,\nquem entrou e quem chegou." },
      { layout: "cta", body: "Diagnóstico grátis.\nPercurso por pagamento único.\n\nfreeme.viviannedossantos.com" },
    ],
    caption: "O FreeMe é uma app que funciona como uma travessia interior.\n\nDiagnóstico grátis. freeme.viviannedossantos.com",
    hashtags: "#FreeMe #ComoFunciona #App #ATravessiaDaMãe #7Bloqueios #DiagnósticoGrátis",
    platforms: ["ig", "tiktok"],
  },
  {
    day: 30, slot: "evening", time: "13:00", type: "carousel", categoria: "cta",
    title: "Não vieste tarde",
    slides: [
      { layout: "capa", body: "Não vieste tarde.\nVieste a tempo de ti.", bold: ["a tempo de ti"] },
      { layout: "conteudo", body: "A travessia começa quando tu decidires pousar o que não é teu." },
      { layout: "citacao", body: "A culpa não é boa conselheira." },
      { layout: "cta", body: "Diagnóstico grátis.\n\nfreeme.viviannedossantos.com" },
      { layout: "assinatura", body: "FreeMe\nA Travessia da Mãe\nVivianne dos Santos" },
    ],
    caption: "Não vieste tarde. Vieste a tempo de ti.\n\nDiagnóstico grátis: freeme.viviannedossantos.com\n\nPartilha com uma mãe que precisa.",
    hashtags: "#FreeMe #NãoViesteTarde #ATravessiaDaMãe #MãeSemCulpa #ConstelacaoFamiliar #DiagnósticoGrátis",
    platforms: ["ig", "tiktok"],
  },
];
