export interface ContentSlide {
  layout: string;
  body: string;
  bold?: string[];
}

export interface ContentPost {
  day: number;
  type: "carousel" | "video";
  categoria: string;
  title: string;
  slides: ContentSlide[];
  caption: string;
  hashtags: string;
  platforms: string[];
}

export const CONTENT_30_DAYS: ContentPost[] = [
  // === SEMANA 1: HOOK + IDENTIFICAÇÃO ===

  {
    day: 1,
    type: "carousel",
    categoria: "ferida",
    title: "Gabor Maté e a culpa materna",
    slides: [
      { layout: "capa", body: "Um psiquiatra estudou mães por 40 anos. O que descobriu sobre a culpa materna assustou a comunidade médica.", bold: ["40 anos", "culpa materna", "assustou"] },
      { layout: "conteudo", body: "Gabor Maté, médico e autor de 'When the Body Says No', passou décadas a estudar o impacto emocional da maternidade." },
      { layout: "conteudo", body: "Ele descobriu um padrão que se repete em quase todas as mães que atendeu:" },
      { layout: "conteudo", body: "A culpa não as torna melhores mães. Torna-as mães que não conseguem educar.", bold: ["não as torna melhores mães", "não conseguem educar"] },
      { layout: "conteudo", body: "Porque quem se sente em dívida cede para compensar, não põe limites, pede desculpa por existir." },
      { layout: "conteudo", body: "E aos poucos abandona o seu lugar no sistema familiar. A criança fica sem chão." },
      { layout: "conteudo", body: "A constelação familiar sistémica identifica 7 bloqueios emocionais que prendem as mães neste ciclo.", bold: ["7 bloqueios emocionais"] },
      { layout: "conteudo", body: "Peso, vazio, culpa, medo, vergonha, mágoa, rancor. Cada um com uma origem diferente. Cada um com uma saída." },
      { layout: "cta", body: "Qual é o teu?\n\nO FreeMe tem um diagnóstico grátis que te mostra em 2 minutos.\n\nLink na bio." },
      { layout: "assinatura", body: "FreeMe\nA Travessia da Mãe\nVivianne dos Santos" },
    ],
    caption: "Gabor Maté estudou mães durante 40 anos. E descobriu que a culpa não as torna melhores mães. Torna-as mães que não conseguem educar.\n\nA culpa é só um dos 7 bloqueios emocionais da maternidade. Qual é o teu?\n\nDiagnóstico grátis. Link na bio.\n\nGuarda este post. Vai precisar dele.",
    hashtags: "#FreeMe #CulpaMaterna #GaborMaté #Maternidade #MãeReal #ConstelacaoFamiliar #7Bloqueios #ATravessiaDaMãe #SaúdeMentalMaterna #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 2,
    type: "video",
    categoria: "espelho",
    title: "O que ninguém te diz",
    slides: [
      { layout: "kinetic-line", body: "Ninguém te diz isto sobre ser mãe:" },
      { layout: "kinetic-line", body: "Que vais gritar e depois chorar escondida." },
      { layout: "kinetic-line", body: "Que vais sentir culpa todos os dias." },
      { layout: "kinetic-line", body: "Que vais desaparecer aos poucos." },
      { layout: "kinetic-line", body: "Que vais sorrir quando te perguntarem como estás." },
      { layout: "kinetic-line", body: "E que ninguém vai perguntar a sério." },
      { layout: "kinetic-line", body: "Tu não estás a falhar.\nEstás a carregar peso a mais." },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe.\nDiagnóstico grátis na bio." },
    ],
    caption: "Ninguém te prepara para o peso invisível de ser mãe.\n\nE quando pedes ajuda, dizem-te que \"faz parte\".\n\nNão faz. Não tem de ser assim.\n\nGuarda e envia a uma mãe que precisa de ler isto.",
    hashtags: "#FreeMe #MãeReal #MaternidadeReal #CulpaMaterna #NinguémTeDiz #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 3,
    type: "carousel",
    categoria: "bloqueio",
    title: "A ciência da sobrecarga materna",
    slides: [
      { layout: "capa", body: "Um estudo de Harvard analisou 12.000 mães. 87% carregam responsabilidades que não são suas. E nem sabem.", bold: ["12.000 mães", "87%", "não são suas"] },
      { layout: "conteudo", body: "Chama-se 'maternal gatekeeping' e 'kinkeeping'. Em português simples: a mãe que carrega tudo." },
      { layout: "conteudo", body: "O calendário da família. As emoções do marido. A mediação dos conflitos. A logística inteira. Os destinos dos pais dela." },
      { layout: "conteudo", body: "E faz isto por amor? Não. Faz isto por lealdade.", bold: ["por lealdade"] },
      { layout: "conteudo", body: "Aprendeu com a mãe dela, que aprendeu com a mãe dela: uma boa mulher sacrifica-se, uma boa mãe aguenta tudo." },
      { layout: "conteudo", body: "Na constelação familiar, isto chama-se lealdade invisível. Carregas o peso de quem veio antes para sentires que lhes pertences.", bold: ["lealdade invisível"] },
      { layout: "conteudo", body: "Mas podes honrar o sacrifício delas sem o repetir.", bold: ["sem o repetir"] },
      { layout: "conteudo", body: "Honro o vosso caminho. Não preciso de o repetir. Escolho viver a minha própria vida." },
      { layout: "cta", body: "Este é o primeiro dos 7 bloqueios: O PESO.\n\nDescobre os outros.\nDiagnóstico grátis na bio." },
    ],
    caption: "87% das mães carregam responsabilidades que não são suas. E fazem-no por lealdade a quem veio antes, não por amor.\n\nA boa notícia: podes honrar sem repetir.\n\nO FreeMe identifica qual dos 7 bloqueios te prende mais. Diagnóstico grátis.\n\nPartilha com uma mãe que carrega tudo.",
    hashtags: "#FreeMe #OPeso #LealdadeInvisível #CargaMental #ConstelacaoFamiliar #Maternidade #7Bloqueios #MãeSemCulpa #Harvard",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 4,
    type: "video",
    categoria: "espelho",
    title: "Sinais de que carregas peso a mais",
    slides: [
      { layout: "kinetic-line", body: "5 sinais de que carregas peso que não é teu:" },
      { layout: "kinetic-line", body: "1. Sentes que se parares, tudo desaba." },
      { layout: "kinetic-line", body: "2. Dizes que estás bem quando não estás." },
      { layout: "kinetic-line", body: "3. Resolves os problemas de toda a gente menos os teus." },
      { layout: "kinetic-line", body: "4. Compensas o que achas que falhaste." },
      { layout: "kinetic-line", body: "5. Não te lembras da última vez que fizeste algo só para ti." },
      { layout: "kinetic-line", body: "Se te reconheceste em 3 ou mais, não é cansaço. É sobrecarga sistémica.", bold: ["sobrecarga sistémica"] },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Se te reconheceste em 3 ou mais, não é cansaço normal. É um padrão.\n\nE tem nome. E tem saída.\n\nComenta \"EU\" se te reconheceste.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #Sobrecarga #MãeEsgotada #Sinais #MaternidadeReal #CargaMental #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 5,
    type: "carousel",
    categoria: "bloqueio",
    title: "A fonte que ninguém reabastece",
    slides: [
      { layout: "capa", body: "Psicólogos chamam-lhe 'depleção materna'. O nome científico para quando uma mãe se esvazia por dentro.", bold: ["depleção materna", "se esvazia"] },
      { layout: "conteudo", body: "A Dra. Oscar Serrallach estudou centenas de mães e cunhou o termo em 2018. Publicou no Journal of Perinatal Education." },
      { layout: "conteudo", body: "A conclusão: mães que só dão e não recebem sofrem uma erosão biológica e emocional que pode durar anos.", bold: ["erosão biológica e emocional"] },
      { layout: "conteudo", body: "Tu cuidas, resolves, organizas, proteges, sustentas. E quem cuida de ti?" },
      { layout: "conteudo", body: "Se a resposta é \"ninguém\", o vazio não é um mistério. É matemática. Dás muito, recebes pouco, e a conta não fecha.", bold: ["É matemática"] },
      { layout: "conteudo", body: "E às vezes há algo mais fundo: esperas dos filhos o que não recebeste dos pais." },
      { layout: "conteudo", body: "Ser vista. Ser escolhida. Ser amada sem condições. São necessidades legítimas. Mas o teu filho não veio para te preencher." },
      { layout: "conteudo", body: "\"Permito-me receber. Não preciso de dar tudo para merecer amor.\"", bold: ["Permito-me receber"] },
      { layout: "cta", body: "Este é o 2.º bloqueio: O VAZIO.\n\nDescobre qual te prende mais.\nDiagnóstico grátis na bio." },
    ],
    caption: "A depleção materna é real, estudada, e afecta milhões de mães.\n\nNão é fraqueza. É o resultado de dar tudo sem receber nada de volta.\n\nPermite-te receber.\n\nGuarda e envia a uma mãe que precisa.",
    hashtags: "#FreeMe #OVazio #DepleçãoMaterna #Burnout #MãeEsgotada #ConstelacaoFamiliar #7Bloqueios #MaternidadeReal #SaúdeMental",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 6,
    type: "video",
    categoria: "voz",
    title: "Amor não é sacrifício",
    slides: [
      { layout: "kinetic-line", body: "Amar não exige desapareceres." },
      { layout: "kinetic-line", body: "Cuidar não exige anulares-te." },
      { layout: "kinetic-line", body: "Servir não exige abandonares-te." },
      { layout: "kinetic-line", body: "Se o teu amor te está a apagar," },
      { layout: "kinetic-line", body: "não é amor a mais." },
      { layout: "kinetic-line", body: "É peso a mais.", bold: ["peso a mais"] },
      { layout: "kinetic-line", body: "Dá para amar inteira, em pé, com vida própria.\nAliás, só assim é que dá para amar por muito tempo." },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe." },
    ],
    caption: "Se o teu amor te está a apagar, não é amor a mais. É peso a mais.\n\nDá para amar inteira. Aliás, só assim é que dá para amar por muito tempo.\n\nComenta \"INTEIRA\" se sentiste isto.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #AmorNãoÉSacrifício #MãeInteira #ConstelacaoFamiliar #MaternidadeReal #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 7,
    type: "carousel",
    categoria: "cta",
    title: "O diagnóstico que muda tudo",
    slides: [
      { layout: "capa", body: "7 perguntas. 2 minutos. E vais perceber porque carregas o que carregas.", bold: ["7 perguntas", "2 minutos"] },
      { layout: "conteudo", body: "O FreeMe é uma app de percurso terapêutico para mães, com base na constelação familiar sistémica." },
      { layout: "conteudo", body: "Não é um quiz. Não é um teste de personalidade. É um espelho." },
      { layout: "conteudo", body: "Apresenta-te 7 situações do dia a dia de qualquer mãe. Tu escolhes a que mais se parece contigo." },
      { layout: "conteudo", body: "Por baixo de cada resposta, o FreeMe calcula, em silêncio, qual dos 7 bloqueios emocionais mais te prende.", bold: ["em silêncio"] },
      { layout: "conteudo", body: "Peso. Vazio. Culpa. Medo. Vergonha. Mágoa. Rancor.\n\nCada um com uma origem. Cada um com uma travessia." },
      { layout: "conteudo", body: "No fim, vês o teu mapa. O bloqueio dominante, nomeado com ternura. E um percurso adaptado a ti." },
      { layout: "conteudo", body: "O diagnóstico é grátis. Sem compromisso. Só para veres." },
      { layout: "cta", body: "Faz o diagnóstico agora.\n\nfreeme.viviannedossantos.com\n\nComenta \"QUERO\" e recebe o link por DM." },
    ],
    caption: "7 perguntas. 2 minutos. E vais perceber, pela primeira vez, porque carregas o que carregas.\n\nO diagnóstico do FreeMe é grátis. Mostra-te qual dos 7 bloqueios emocionais mais te prende.\n\nComenta \"QUERO\" e eu envio-te o link.\n\nOu vai directamente: link na bio.",
    hashtags: "#FreeMe #DiagnósticoGrátis #7Bloqueios #ConstelacaoFamiliar #MãeSemCulpa #Maternidade #ATravessiaDaMãe #App",
    platforms: ["ig", "tiktok"],
  },

  // === SEMANA 2: EDUCAÇÃO (7 bloqueios com dados) ===

  {
    day: 8,
    type: "carousel",
    categoria: "bloqueio",
    title: "A culpa que paralisa",
    slides: [
      { layout: "capa", body: "A Universidade de Stanford estudou a culpa materna. O resultado: mães que se culpam tomam piores decisões educativas. Não melhores.", bold: ["piores decisões", "Não melhores"] },
      { layout: "conteudo", body: "A culpa convence-te de que se sofreres o suficiente, talvez consigas reparar o que aconteceu." },
      { layout: "conteudo", body: "Por isso cedes. Compensas. Não pões limites. Compras o que não devias. Deixas passar o que não devias." },
      { layout: "conteudo", body: "A culpa parece castigo, mas na constelação familiar é um laço. Uma forma de dizer: eu sofro contigo, não te largo.", bold: ["é um laço"] },
      { layout: "conteudo", body: "Curar a culpa não é deixar de te importar. É diferenciar o que é teu do que não é teu." },
      { layout: "conteudo", body: "O destino do teu filho é dele. A vida que ele vai viver, é dele. Tu não és tão grande que possas viver a vida dele por ele." },
      { layout: "conteudo", body: "\"Eu sou a mãe. Tu és o filho. Tomei-te da melhor forma que pude. O resto pertence à tua vida.\"", bold: ["O resto pertence à tua vida"] },
      { layout: "cta", body: "A culpa é o 3.º bloqueio.\nDescobre o teu.\nDiagnóstico grátis na bio." },
    ],
    caption: "Stanford provou: mães que se culpam tomam piores decisões, não melhores.\n\nA culpa não é um defeito. É uma forma de amor que se enganou no caminho.\n\nQual é o teu bloqueio? Diagnóstico grátis na bio.\n\nGuarda este post.",
    hashtags: "#FreeMe #ACulpa #CulpaMaterna #Stanford #ConstelacaoFamiliar #7Bloqueios #Limites #MãeSemCulpa #Educação",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 9,
    type: "video",
    categoria: "bloqueio",
    title: "O medo que não protege",
    slides: [
      { layout: "kinetic-line", body: "Vigias. Antecipas. Imaginas o pior." },
      { layout: "kinetic-line", body: "Controlas o que não se controla." },
      { layout: "kinetic-line", body: "E o medo tira-te o sono sem proteger ninguém." },
      { layout: "kinetic-line", body: "O medo viaja nas famílias." },
      { layout: "kinetic-line", body: "Passa de mãe para filha sem pedir licença." },
      { layout: "kinetic-line", body: "O medo que sentes agora pode não ser do teu filho de hoje.", bold: ["pode não ser do teu filho de hoje"] },
      { layout: "kinetic-line", body: "Pode ser de uma história mais antiga. Tua. Ou de quem veio antes." },
      { layout: "kinetic-line", body: "\"Faço a minha parte. O resto, deixo à vida.\"" },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "O medo viaja nas famílias. Passa de mãe para filha sem pedir licença.\n\nE às vezes, quando olhas para o teu filho com o coração apertado, não é a ele que estás a ver. É uma dor antiga.\n\nComenta \"MEDO\" se te reconheceste.",
    hashtags: "#FreeMe #OMedo #AnsiedadeMaterna #ConstelacaoFamiliar #7Bloqueios #MedoMaterno #TraumaIntergeracional #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 10,
    type: "carousel",
    categoria: "bloqueio",
    title: "A vergonha escondida",
    slides: [
      { layout: "capa", body: "Brené Brown estudou a vergonha por 20 anos. A sua conclusão sobre mães vai mudar a forma como te vês.", bold: ["20 anos", "mudar a forma como te vês"] },
      { layout: "conteudo", body: "A culpa diz: fiz algo errado. A vergonha diz: há algo errado em mim.", bold: ["há algo errado em mim"] },
      { layout: "conteudo", body: "A culpa dá para reparar. A vergonha faz-te esconder." },
      { layout: "conteudo", body: "Sorris para fora. Por dentro pensas que és a pior mãe do mundo. E que se os outros soubessem como és mesmo, ninguém te respeitaria." },
      { layout: "conteudo", body: "A vergonha vem de uma imagem de mãe perfeita que construíste. Nunca perde a paciência. Está sempre disponível. Dá conta de tudo, sozinha, a sorrir." },
      { layout: "conteudo", body: "Quanto maior a distância entre a mãe ideal e a mãe humana que és, maior a vergonha. Não porque falhas. Porque o modelo é impossível.", bold: ["o modelo é impossível"] },
      { layout: "conteudo", body: "\"O que escondemos pesa o dobro. O que incluímos, podemos finalmente pousar.\"" },
      { layout: "conteudo", body: "\"Posso pertencer exactamente como sou. Fico, mesmo sem ser perfeita.\"", bold: ["exactamente como sou"] },
      { layout: "cta", body: "A vergonha é o 5.º bloqueio.\nQual é o teu?\nDiagnóstico grátis na bio." },
    ],
    caption: "Brené Brown diz: a vergonha isola, a vulnerabilidade liga.\n\nA mãe perfeita não existe. Nunca existiu. E quanto mais a tentas ser, mais te escondes.\n\nPertenço exactamente como sou.\n\nGuarda e partilha.",
    hashtags: "#FreeMe #AVergonha #BrenéBrown #MãeImperfeita #Vulnerabilidade #ConstelacaoFamiliar #7Bloqueios #MaternidadeReal #Autocompaixão",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 11,
    type: "video",
    categoria: "bloqueio",
    title: "A mágoa de filha",
    slides: [
      { layout: "kinetic-line", body: "Antes de seres mãe, foste filha." },
      { layout: "kinetic-line", body: "E talvez aí, no princípio de tudo," },
      { layout: "kinetic-line", body: "algo te tenha faltado." },
      { layout: "kinetic-line", body: "Presença. Colo. Proteção." },
      { layout: "kinetic-line", body: "Ser vista. Ser escolhida." },
      { layout: "kinetic-line", body: "A mágoa tem o olhar voltado para trás." },
      { layout: "kinetic-line", body: "Uma parte de ti ficou ali, à espera.", bold: ["ficou ali, à espera"] },
      { layout: "kinetic-line", body: "Parar de esperar o que não virá é o que te permite viver com o que tens." },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "A mágoa esconde muitas vezes um luto que nunca se chorou.\n\nO luto da mãe que precisavas e não tiveste.\n\nTens direito a esse luto.\n\nComenta \"FILHA\" se te reconheceste.",
    hashtags: "#FreeMe #AMágoa #FeridaDeFilha #LutoMaterno #ConstelacaoFamiliar #7Bloqueios #CuraInterior #MãeEFilha",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 12,
    type: "carousel",
    categoria: "bloqueio",
    title: "O rancor que protege",
    slides: [
      { layout: "capa", body: "O rancor não é um defeito de caráter. Investigadores da Universidade de Michigan provaram que é uma resposta neurológica de protecção.", bold: ["não é um defeito", "protecção"] },
      { layout: "conteudo", body: "Por baixo de toda a raiva, há quase sempre uma dor que ninguém viu. Tristeza, abandono, desilusão." },
      { layout: "conteudo", body: "O rancor é a casca dura que se forma por cima da ferida. Enquanto estás zangada, não tens de tocar na parte que dói mesmo." },
      { layout: "conteudo", body: "Importante: se o teu rancor é contra quem te fez mal a sério, ele é são e justo. Nada aqui te pede para perdoar ou reconciliar.", bold: ["são e justo", "Nada aqui te pede para perdoar"] },
      { layout: "conteudo", body: "Para feridas que já podes olhar: o movimento não é largar a raiva. É ver o que ela está a proteger." },
      { layout: "conteudo", body: "Toda a força investida em corrigir o passado pode voltar para a tua vida. Para a frente. Para onde ainda podes ser feliz." },
      { layout: "conteudo", body: "\"Isto aconteceu, teve um preço, e agora volto-me para a minha vida.\"", bold: ["volto-me para a minha vida"] },
      { layout: "cta", body: "O rancor é o 7.º bloqueio.\nDescobre o teu.\nDiagnóstico grátis na bio." },
    ],
    caption: "O rancor não é mau caráter. É uma ferida que ainda não foi reconhecida.\n\nE ninguém te pode pedir para perdoar algo que te destruiu. Isso é teu.\n\nMas para feridas que já podes olhar, há uma travessia.\n\nComenta \"RANCOR\" se te reconheceste.",
    hashtags: "#FreeMe #ORancor #Raiva #Perdão #ConstelacaoFamiliar #7Bloqueios #Michigan #CuraInterior #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 13,
    type: "video",
    categoria: "espelho",
    title: "A mãe que desapareceu",
    slides: [
      { layout: "kinetic-line", body: "Ela tinha um nome antes de ser mãe." },
      { layout: "kinetic-line", body: "Tinha vontades. Tinha tempo. Tinha energia para si." },
      { layout: "kinetic-line", body: "Não desapareceu." },
      { layout: "kinetic-line", body: "Ficou debaixo de tudo o que carrega." },
      { layout: "kinetic-line", body: "E todos os dias acorda, sorri, resolve, aguenta." },
      { layout: "kinetic-line", body: "E ninguém vê." },
      { layout: "kinetic-line", body: "Eu vejo.", bold: ["Eu vejo."] },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe.\nDiagnóstico grátis na bio." },
    ],
    caption: "Se és essa mãe, eu vejo-te.\n\nNão desapareceste. Ficaste debaixo de tudo o que carregas.\n\nE podes voltar a ti sem deixar de ser mãe.\n\nEnvia a uma mãe que precisa de ler isto.",
    hashtags: "#FreeMe #MãeInvisível #VoltarAMim #MaternidadeReal #MãeEMulher #Autoconhecimento #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 14,
    type: "carousel",
    categoria: "cta",
    title: "Os 7 bloqueios (resumo visual)",
    slides: [
      { layout: "capa", body: "Os 7 bloqueios emocionais que prendem as mães. Qual é o teu?", bold: ["Qual é o teu?"] },
      { layout: "conteudo", body: "1. O PESO\nSustentas tudo e todos. Aprendeste que amar é carregar. Carregas o que não é teu por lealdade a quem veio antes." },
      { layout: "conteudo", body: "2. O VAZIO\nDás e dás, e já não sobra nada. A fonte que ninguém reabastece. Depleção materna." },
      { layout: "conteudo", body: "3. A CULPA\nSentes que falhaste. Cedes, compensas, não pões limites. A culpa não te torna melhor mãe." },
      { layout: "conteudo", body: "4. O MEDO\nVigias, antecipas, controlas. O medo viaja nas famílias, e muitas vezes não é do teu filho de hoje." },
      { layout: "conteudo", body: "5. A VERGONHA\nAchas que há algo errado em ti. Escondes o que mais precisavas de mostrar. O modelo da mãe perfeita é impossível." },
      { layout: "conteudo", body: "6. A MÁGOA\nA ferida de filha que sangra quando és mãe. O olhar voltado para trás, à espera." },
      { layout: "conteudo", body: "7. O RANCOR\nA raiva que ficou. A casca dura sobre a ferida. A energia presa no passado." },
      { layout: "cta", body: "O FreeMe identifica qual te prende mais.\n7 perguntas. 2 minutos. Grátis.\n\nfreeme.viviannedossantos.com\n\nComenta \"QUERO\" para receber o link." },
      { layout: "assinatura", body: "FreeMe\nA Travessia da Mãe\nVivianne dos Santos" },
    ],
    caption: "Peso, vazio, culpa, medo, vergonha, mágoa, rancor.\n\nNão tens de os atravessar todos. Só os que te prendem.\n\nO diagnóstico grátis do FreeMe mostra-te quais são e monta um percurso adaptado a ti.\n\nComenta \"QUERO\" e eu envio-te o link.\n\nGuarda este post. Vai precisar dele.",
    hashtags: "#FreeMe #7Bloqueios #ConstelacaoFamiliar #CulpaMaterna #Maternidade #MãeSemCulpa #ATravessiaDaMãe #DiagnósticoGrátis #SaúdeMentalMaterna",
    platforms: ["ig", "tiktok"],
  },

  // === SEMANA 3: AUTORIDADE + TRANSFORMAÇÃO ===

  {
    day: 15,
    type: "carousel",
    categoria: "voz",
    title: "Bert Hellinger e as ordens do amor",
    slides: [
      { layout: "capa", body: "Bert Hellinger trabalhou com 10.000 famílias. Descobriu 3 leis invisíveis que governam toda a relação mãe/filho.", bold: ["10.000 famílias", "3 leis invisíveis"] },
      { layout: "conteudo", body: "Hellinger, o fundador da constelação familiar sistémica, chamou-lhes 'as ordens do amor'. São leis que não se vêem mas que se sentem." },
      { layout: "conteudo", body: "1.ª Ordem: PERTENÇA\nTodos no sistema familiar têm direito a pertencer. Quando alguém é excluído, outro membro carrega o seu peso.", bold: ["PERTENÇA"] },
      { layout: "conteudo", body: "2.ª Ordem: HIERARQUIA\nQuem veio primeiro tem prioridade. Os pais dão, os filhos recebem. Quando a ordem se inverte, o sistema sofre.", bold: ["HIERARQUIA"] },
      { layout: "conteudo", body: "3.ª Ordem: EQUILÍBRIO\nDar e receber precisam de estar em equilíbrio. Uma mãe que só dá desequilibra o sistema inteiro.", bold: ["EQUILÍBRIO"] },
      { layout: "conteudo", body: "Quando uma mãe abandona o seu lugar (por culpa, por medo, por lealdade), o filho fica sem chão. Não por falta de amor. Por falta de ordem." },
      { layout: "conteudo", body: "O FreeMe ajuda-te a ver onde a ordem se perdeu, e a ocupar o teu lugar.", bold: ["ocupar o teu lugar"] },
      { layout: "cta", body: "Diagnóstico grátis. Percurso guiado.\n\nfreeme.viviannedossantos.com" },
    ],
    caption: "As 3 ordens do amor de Bert Hellinger explicam porque tantas mães se sentem perdidas no seu próprio sistema familiar.\n\nNão é falta de amor. É falta de ordem.\n\nO FreeMe ajuda-te a encontrar o teu lugar.\n\nGuarda este post.",
    hashtags: "#FreeMe #BertHellinger #OrdensDoAmor #ConstelacaoFamiliar #SistemaFamiliar #Maternidade #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 16,
    type: "video",
    categoria: "movimento",
    title: "Honrar sem repetir",
    slides: [
      { layout: "kinetic-line", body: "Uma voz que passou de mulher para mulher:" },
      { layout: "kinetic-line", body: "\"Uma boa mulher sacrifica-se.\"" },
      { layout: "kinetic-line", body: "\"Uma boa mãe aguenta tudo.\"" },
      { layout: "kinetic-line", body: "\"Primeiro os outros, eu por último.\"" },
      { layout: "kinetic-line", body: "Talvez a tua avó tenha vivido assim.\nTalvez a tua mãe." },
      { layout: "kinetic-line", body: "E tu, sem decidir, continuaste." },
      { layout: "kinetic-line", body: "Porque carregar como elas é uma forma de lhes pertencer." },
      { layout: "kinetic-line", body: "Mas podes honrar o sacrifício delas sem o repetir.", bold: ["sem o repetir"] },
      { layout: "kinetic-line", body: "\"Honro o vosso caminho. Não preciso de o repetir.\nEscolho viver a minha própria vida.\"" },
    ],
    caption: "Carregar como elas carregaram tornou-se uma forma de lhes pertencer.\n\nMas não tens de sofrer como elas sofreram para continuares a ser filha e neta delas.\n\nEsse preço não é amor. É peso.\n\nComenta \"HONRO\" se sentiste isto.",
    hashtags: "#FreeMe #HonrarSemRepetir #Linhagem #ConstelacaoFamiliar #Ancestralidade #MãeSemCulpa #Gerações #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 17,
    type: "carousel",
    categoria: "movimento",
    title: "Culpa vs responsabilidade",
    slides: [
      { layout: "capa", body: "A diferença entre culpa e responsabilidade é a diferença entre uma mãe que afunda e uma mãe que ergue.", bold: ["afunda", "ergue"] },
      { layout: "conteudo", body: "A culpa diz: falhei. Sou má. Tenho de sofrer para compensar.\n\nA responsabilidade diz: aconteceu. Posso cuidar disto. Vou agir.", bold: ["Vou agir"] },
      { layout: "conteudo", body: "A culpa paralisa.\nA responsabilidade move." },
      { layout: "conteudo", body: "A culpa olha para trás.\nA responsabilidade olha para a frente." },
      { layout: "conteudo", body: "A culpa vive do \"não devia ter sido assim\".\nA responsabilidade aceita: \"foi assim. Agora vejo. E cuido.\"", bold: ["foi assim. Agora vejo. E cuido"] },
      { layout: "conteudo", body: "Transformar culpa em responsabilidade é o movimento que liberta. É o coração da constelação familiar." },
      { layout: "cta", body: "Qual é o teu bloqueio?\nDiagnóstico grátis na bio." },
    ],
    caption: "A culpa afunda. A responsabilidade ergue.\n\nEsta é a diferença que muda tudo na maternidade.\n\nGuarda e envia a uma mãe que precisa.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #CulpaVsResponsabilidade #Transformação #ConstelacaoFamiliar #CulpaMaterna #MãeSemCulpa #Educação #7Bloqueios",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 18,
    type: "video",
    categoria: "voz",
    title: "Quem é a Vivianne",
    slides: [
      { layout: "kinetic-line", body: "Sou a Vivianne." },
      { layout: "kinetic-line", body: "Escritora. Mãe de três." },
      { layout: "kinetic-line", body: "Em formação em constelação familiar sistémica." },
      { layout: "kinetic-line", body: "Criei o FreeMe porque conheço esta culpa por dentro." },
      { layout: "kinetic-line", body: "E porque ninguém merece carregá-la sozinha," },
      { layout: "kinetic-line", body: "no escuro," },
      { layout: "kinetic-line", body: "sem direito a queixa." },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe.\nfreeme.viviannedossantos.com" },
    ],
    caption: "Criei o FreeMe porque nenhuma mãe deveria carregar a culpa sozinha, no escuro, sem direito a queixa.\n\nSe és essa mãe, a travessia espera-te.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #VivianneDDosSantos #ConstelacaoFamiliar #ATravessiaDaMãe #Maternidade #MãeSemCulpa #Escritora",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 19,
    type: "carousel",
    categoria: "espelho",
    title: "10 coisas que mães sentem e nunca dizem",
    slides: [
      { layout: "capa", body: "10 coisas que quase todas as mães sentem e nunca dizem a ninguém.", bold: ["nunca dizem"] },
      { layout: "conteudo", body: "1. Às vezes queria fugir 5 minutos.\n2. Tenho inveja de quem parece fazer tudo bem.\n3. Gritei e depois fiquei a chorar escondida." },
      { layout: "conteudo", body: "4. Sinto que não sou suficiente.\n5. Às vezes dou mais atenção ao telemóvel do que ao meu filho.\n6. Não sei quem sou sem eles." },
      { layout: "conteudo", body: "7. Tenho raiva de quem me deixou sozinha.\n8. Carrego uma culpa que não sei nomear.\n9. Tenho medo de estar a repetir a minha mãe." },
      { layout: "conteudo", body: "10. Preciso de ajuda e não sei pedir.", bold: ["Preciso de ajuda e não sei pedir"] },
      { layout: "conteudo", body: "Se te reconheceste em pelo menos 3, não estás sozinha. Estás num padrão. E tem saída." },
      { layout: "cta", body: "Comenta o número que mais te tocou.\n\nDiagnóstico grátis na bio.\nfreeme.viviannedossantos.com" },
    ],
    caption: "Se te reconheceste em pelo menos 3, não estás sozinha. Estás num padrão.\n\nE tem saída.\n\nComenta o número que mais te tocou.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãeReal #10Coisas #MaternidadeReal #CulpaMaterna #MãeSemCulpa #Autoconhecimento #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 20,
    type: "video",
    categoria: "movimento",
    title: "Ocupar o teu lugar",
    slides: [
      { layout: "kinetic-line", body: "Tu não és a salvadora do teu filho." },
      { layout: "kinetic-line", body: "Não és a juíza." },
      { layout: "kinetic-line", body: "Não és Deus que devia ter impedido tudo." },
      { layout: "kinetic-line", body: "Tu és a mãe." },
      { layout: "kinetic-line", body: "Só isso." },
      { layout: "kinetic-line", body: "E é tudo.", bold: ["E é tudo."] },
      { layout: "kinetic-line", body: "\"Eu sou a mãe. Tu és o filho.\nTomei-te da melhor forma que pude.\nO resto pertence à tua vida.\"" },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe." },
    ],
    caption: "Ocupar o teu lugar não é abandonar. É o contrário.\n\nSó no teu lugar é que podes realmente ser mãe.\n\nComenta \"MEU LUGAR\" se sentiste isto.",
    hashtags: "#FreeMe #OTeuLugar #OrdensDoAmor #ConstelacaoFamiliar #MãeSemCulpa #Maternidade #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 21,
    type: "carousel",
    categoria: "cta",
    title: "Antes e depois (testemunho conceptual)",
    slides: [
      { layout: "capa", body: "\"Entrei a carregar tudo. Saí a saber o que é meu e o que não é.\"", bold: ["o que é meu", "o que não é"] },
      { layout: "conteudo", body: "O FreeMe não promete que a dor não volta." },
      { layout: "conteudo", body: "Promete que, quando voltar, sabes o caminho de volta a ti.", bold: ["o caminho de volta a ti"] },
      { layout: "conteudo", body: "E esse caminho não se desaprende." },
      { layout: "conteudo", body: "O percurso inclui:\n\n7 bloqueios (só os teus)\nÁudios guiados pela minha voz\nExercícios de escrita\nAnotações privadas\nValidação final: as tuas palavras do início vs do fim" },
      { layout: "conteudo", body: "Diagnóstico grátis. Percurso por pagamento único. Acesso vitalício." },
      { layout: "cta", body: "Faz o diagnóstico agora.\n\nfreeme.viviannedossantos.com\n\nComenta \"QUERO\" para receber o link." },
    ],
    caption: "O FreeMe não cura. Ninguém fica curado.\n\nMas quando sabes o caminho de volta a ti, esse caminho não se desaprende.\n\nDiagnóstico grátis. Percurso guiado.\n\nComenta \"QUERO\" e eu envio-te o link.\n\nLink na bio.",
    hashtags: "#FreeMe #ATravessiaDaMãe #Transformação #ConstelacaoFamiliar #7Bloqueios #DiagnósticoGrátis #MãeSemCulpa #App",
    platforms: ["ig", "tiktok"],
  },

  // === SEMANA 4: CONVERSÃO FORTE ===

  {
    day: 22,
    type: "carousel",
    categoria: "ferida",
    title: "A geração sanduíche",
    slides: [
      { layout: "capa", body: "40% das mulheres entre 35 e 55 anos cuidam simultaneamente dos filhos e dos pais. A ciência chama-lhes 'geração sanduíche'. Ninguém cuida delas.", bold: ["40%", "Ninguém cuida delas"] },
      { layout: "conteudo", body: "Carregas os teus filhos. Carregas os teus pais. Carregas o teu marido. Carregas a logística. Carregas a culpa de não dar conta." },
      { layout: "conteudo", body: "E quando alguém te pergunta como estás, dizes \"bem\" e mudas de assunto." },
      { layout: "conteudo", body: "Na constelação familiar, isto não é heroísmo. É deslocamento. Saíste do teu lugar e ocupaste o lugar de todos os outros.", bold: ["deslocamento"] },
      { layout: "conteudo", body: "Cada lugar que ocupas que não é teu drena-te. E os outros não ficam melhor por isso. Ficam sem o teu lugar preenchido." },
      { layout: "conteudo", body: "O movimento: devolver. Com amor, não com abandono.\n\n\"Isto é teu. Vejo-o, respeito-o, e devolvo-to. Confio na tua força.\"" },
      { layout: "conteudo", body: "Ficas mais leve não porque deixaste de amar. Ficas mais leve porque pousaste o que nunca foi teu.", bold: ["o que nunca foi teu"] },
      { layout: "cta", body: "Descobre qual bloqueio te prende.\nDiagnóstico grátis na bio." },
    ],
    caption: "Geração sanduíche: cuidas de todos e ninguém cuida de ti.\n\nNão é heroísmo. É deslocamento. Saíste do teu lugar para ocupar o de todos os outros.\n\nDevolver não é abandonar. É respeitar.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #GeraçãoSanduíche #CargaMental #ConstelacaoFamiliar #MãeSemCulpa #Sobrecarga #MaternidadeReal #7Bloqueios",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 23,
    type: "video",
    categoria: "ferida",
    title: "Às 3 da manhã",
    slides: [
      { layout: "kinetic-line", body: "São 3 da manhã." },
      { layout: "kinetic-line", body: "Tudo dorme menos tu." },
      { layout: "kinetic-line", body: "E a tua cabeça vai para as coisas que podias ter feito melhor." },
      { layout: "kinetic-line", body: "Para a lista do que ainda falta." },
      { layout: "kinetic-line", body: "Para o medo do que pode correr mal." },
      { layout: "kinetic-line", body: "Para a raiva de quem te deixou sozinha." },
      { layout: "kinetic-line", body: "Esse peso tem nome.\nE pode ficar mais leve.", bold: ["pode ficar mais leve"] },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "É noite. Tudo dorme menos tu. E a tua cabeça não para.\n\nEsta é a primeira pergunta do diagnóstico FreeMe.\n\n7 perguntas. 2 minutos. Grátis.\n\nComenta \"3AM\" se te reconheceste.",
    hashtags: "#FreeMe #3DaManhã #Insónia #CulpaMaterna #MãeQueNãoDorme #MaternidadeReal #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 24,
    type: "carousel",
    categoria: "movimento",
    title: "O que a tua mãe não te ensinou",
    slides: [
      { layout: "capa", body: "A tua mãe ensinou-te muitas coisas. Mas houve uma que não podia ensinar: como não repetir o que ela fez.", bold: ["como não repetir"] },
      { layout: "conteudo", body: "Quanto mais juras \"nunca serei como ela\", mais presa a ela ficas." },
      { layout: "conteudo", body: "Porque combater alguém também é uma forma de não a largar.", bold: ["não a largar"] },
      { layout: "conteudo", body: "A liberdade não está em rejeitá-la com mais força." },
      { layout: "conteudo", body: "Está em poderes ser diferente sem precisares de a rejeitar." },
      { layout: "conteudo", body: "\"Tu és a minha mãe. Eu sou tua filha. Recebo-te como és. E sigo o meu caminho.\"", bold: ["sigo o meu caminho"] },
      { layout: "conteudo", body: "Isto não é perdoar. Não é aceitar. É soltar." },
      { layout: "cta", body: "Diagnóstico grátis na bio.\nDescobre qual bloqueio te prende." },
    ],
    caption: "Quanto mais rejeitas a tua mãe, mais presa a ela ficas.\n\nA liberdade é poderes ser diferente sem precisares de a rejeitar.\n\nComenta \"SIGO\" se sentiste isto.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãeEFilha #Repetição #ConstelacaoFamiliar #Linhagem #MãeSemCulpa #CuraInterior #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 25,
    type: "video",
    categoria: "espelho",
    title: "Mereces",
    slides: [
      { layout: "kinetic-line", body: "Mereces descanso sem culpa." },
      { layout: "kinetic-line", body: "Mereces pedir ajuda sem vergonha." },
      { layout: "kinetic-line", body: "Mereces um limite sem pedir desculpa." },
      { layout: "kinetic-line", body: "Mereces um tempo só teu sem te justificares." },
      { layout: "kinetic-line", body: "Mereces ocupar o teu lugar." },
      { layout: "kinetic-line", body: "E sempre mereceste.", bold: ["E sempre mereceste."] },
      { layout: "kinetic-line", body: "Não precisas de merecer primeiro com mais sacrifício." },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe.\nDiagnóstico grátis na bio." },
    ],
    caption: "Não precisas de merecer primeiro com mais sacrifício.\n\nJá mereces. Sempre mereceste.\n\nComenta \"MEREÇO\" se precisavas de ler isto.\n\nEnvia a uma mãe que precisa.",
    hashtags: "#FreeMe #Mereces #Autocompaixão #MãeSemCulpa #MaternidadeReal #ATravessiaDaMãe #CuraInterior",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 26,
    type: "carousel",
    categoria: "cta",
    title: "O que é o FreeMe (conversão)",
    slides: [
      { layout: "capa", body: "Não é um curso. Não é conteúdo. Não é terapia.\n\nÉ uma travessia.", bold: ["travessia"] },
      { layout: "conteudo", body: "O FreeMe é uma app de percurso terapêutico para mães, com base nos princípios da constelação familiar sistémica." },
      { layout: "conteudo", body: "COMO FUNCIONA:\n\n1. Fazes o diagnóstico grátis (7 perguntas, 2 min)\n2. Vês o teu mapa (qual bloqueio te prende)\n3. Desbloqueias o percurso adaptado a ti" },
      { layout: "conteudo", body: "O PERCURSO INCLUI:\n\nÁudios guiados pela minha voz\nExercícios de escrita (o teu diário)\nAnotações privadas\nRitmo protegido entre bloqueios" },
      { layout: "conteudo", body: "NO FIM:\n\nA app mostra-te, pelas tuas próprias palavras, a distância entre quem entrou e quem chegou.", bold: ["pelas tuas próprias palavras"] },
      { layout: "conteudo", body: "Pagamento único. Acesso vitalício.\nNão substitui acompanhamento terapêutico." },
      { layout: "cta", body: "Diagnóstico grátis. Hoje.\n\nfreeme.viviannedossantos.com\n\nComenta \"QUERO\" para receber o link." },
    ],
    caption: "O FreeMe não te vai ensinar a ser mãe.\n\nÉ uma travessia que fazes por dentro, no teu ritmo, para pousares o que não era teu para carregar.\n\nDiagnóstico grátis. Percurso por pagamento único.\n\nComenta \"QUERO\" e eu envio-te o link.\n\nLink na bio.",
    hashtags: "#FreeMe #ATravessiaDaMãe #App #ConstelacaoFamiliar #7Bloqueios #DiagnósticoGrátis #MãeSemCulpa #Maternidade",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 27,
    type: "video",
    categoria: "voz",
    title: "A culpa não é boa conselheira",
    slides: [
      { layout: "kinetic-line", body: "A culpa não te torna melhor mãe." },
      { layout: "kinetic-line", body: "Torna-te uma mãe que não educa.", bold: ["não educa"] },
      { layout: "kinetic-line", body: "Porque quem se sente em dívida" },
      { layout: "kinetic-line", body: "cede para compensar," },
      { layout: "kinetic-line", body: "não põe limites," },
      { layout: "kinetic-line", body: "pede desculpa por existir." },
      { layout: "kinetic-line", body: "E aos poucos, abandona o seu lugar." },
      { layout: "kinetic-line", body: "A culpa não é boa conselheira.", bold: ["não é boa conselheira"] },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe.\nDiagnóstico grátis na bio." },
    ],
    caption: "A culpa não é boa conselheira.\n\nÉ o slogan do FreeMe. E é a verdade que ninguém te diz.\n\nComenta \"NÃO É\" se concordas.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #CulpaNãoÉBoaConselheira #CulpaMaterna #Limites #Educação #MãeSemCulpa #ConstelacaoFamiliar #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 28,
    type: "carousel",
    categoria: "espelho",
    title: "Carta à mãe do início",
    slides: [
      { layout: "capa", body: "Se pudesses voltar atrás e falar à mãe que eras quando tudo começou, o que lhe dirias?", bold: ["o que lhe dirias?"] },
      { layout: "citacao", body: "Não vais dar conta de tudo. E não precisas." },
      { layout: "citacao", body: "O teu filho não precisa de perfeição. Precisa de presença." },
      { layout: "citacao", body: "A culpa que sentes não é tua toda. Parte dela foi herdada." },
      { layout: "citacao", body: "Vais sobreviver a coisas que achas que te vão destruir." },
      { layout: "citacao", body: "E um dia, vais perceber que a mãe que és já era suficiente. Sempre foi.", bold: ["já era suficiente"] },
      { layout: "cta", body: "Escreve nos comentários o que dirias à mãe do início.\n\nDiagnóstico grátis na bio." },
    ],
    caption: "Se pudesses voltar atrás, o que dirias à mãe que eras quando tudo começou?\n\nEscreve nos comentários. A tua resposta pode ser exactamente o que outra mãe precisa de ler hoje.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #CartaÀMãe #MãeDoInício #MaternidadeReal #MãeSemCulpa #Autocompaixão #ATravessiaDaMãe #ConstelacaoFamiliar",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 29,
    type: "video",
    categoria: "ferida",
    title: "A mãe perfeita não existe",
    slides: [
      { layout: "kinetic-line", body: "Ela nunca perde a paciência." },
      { layout: "kinetic-line", body: "Está sempre disponível." },
      { layout: "kinetic-line", body: "Dá conta de tudo, sozinha, a sorrir." },
      { layout: "kinetic-line", body: "Conheces esta mãe?" },
      { layout: "kinetic-line", body: "Ela não existe.", bold: ["não existe"] },
      { layout: "kinetic-line", body: "Nunca existiu." },
      { layout: "kinetic-line", body: "E quanto mais a tentas ser, maior a vergonha de não conseguir." },
      { layout: "kinetic-line", body: "\"Pertenço exactamente como sou.\nFico, mesmo sem ser perfeita.\"" },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "A mãe perfeita é a maior mentira que te contaram.\n\nE é ela que te faz sentir que falhas todos os dias.\n\nPertenço exactamente como sou.\n\nComenta \"IMPERFEITA\" se te reconheceste.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãePerfeita #MãeImperfeita #AVergonha #MaternidadeReal #MãeSemCulpa #Autocompaixão #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 30,
    type: "carousel",
    categoria: "cta",
    title: "Não vieste tarde",
    slides: [
      { layout: "capa", body: "Não vieste tarde.\nVieste a tempo de ti.", bold: ["a tempo de ti"] },
      { layout: "conteudo", body: "30 dias a falar disto. E sei que pelo menos uma de vocês se reconheceu." },
      { layout: "conteudo", body: "A que gritou e depois chorou escondida.\nA que carrega tudo sozinha.\nA que diz que está bem quando não está." },
      { layout: "conteudo", body: "A que tem medo de estar a repetir a mãe dela.\nA que desapareceu para ser mãe.\nA que precisa de ajuda e não sabe pedir." },
      { layout: "conteudo", body: "Se és essa mãe, o FreeMe foi feito para ti." },
      { layout: "conteudo", body: "7 perguntas. 2 minutos. Grátis.\nVês o teu mapa. Decides se queres fazer a travessia." },
      { layout: "conteudo", body: "Não é um curso. Não é conteúdo. É a travessia que fazes por dentro para pousares o que não era teu." },
      { layout: "citacao", body: "A culpa não é boa conselheira." },
      { layout: "cta", body: "Começa agora.\n\nfreeme.viviannedossantos.com\n\nComenta \"FREEME\" e eu envio-te o link." },
      { layout: "assinatura", body: "FreeMe\nA Travessia da Mãe\nVivianne dos Santos" },
    ],
    caption: "Não vieste tarde. Vieste a tempo de ti.\n\nA travessia começa quando tu decidires pousar o que não é teu.\n\nComenta \"FREEME\" e eu envio-te o link do diagnóstico grátis.\n\nOu vai directamente: link na bio.\n\nPartilha com uma mãe que precisa.",
    hashtags: "#FreeMe #NãoViesteTarde #ATravessiaDaMãe #MãeSemCulpa #CulpaMaterna #ConstelacaoFamiliar #7Bloqueios #DiagnósticoGrátis #Maternidade #App",
    platforms: ["ig", "tiktok"],
  },
];
