export interface ContentSlide {
  layout: string;
  body: string;
  bold?: string[];
}

export interface ContentPost {
  day: number;
  type: "carousel" | "video";
  categoria: string;
  title: string;
  slides: ContentSlide[];
  caption: string;
  hashtags: string;
  platforms: string[];
}

export const CONTENT_30_DAYS: ContentPost[] = [
  // === SEMANA 1: HOOK + IDENTIFICAÇÃO ===

  {
    day: 1,
    type: "carousel",
    categoria: "ferida",
    title: "Gabor Maté e a culpa materna",
    slides: [
      { layout: "capa", body: "Um psiquiatra estudou mães por 40 anos. O que descobriu sobre a culpa materna assustou a comunidade médica.", bold: ["40 anos", "culpa materna", "assustou"] },
      { layout: "conteudo", body: "Gabor Maté, médico e autor de 'When the Body Says No', passou décadas a estudar o impacto emocional da maternidade." },
      { layout: "conteudo", body: "Ele descobriu um padrão que se repete em quase todas as mães que atendeu:" },
      { layout: "conteudo", body: "A culpa não as torna melhores mães. Torna-as mães que não conseguem educar.", bold: ["não as torna melhores mães", "não conseguem educar"] },
      { layout: "conteudo", body: "Porque quem se sente em dívida cede para compensar, não põe limites, pede desculpa por existir." },
      { layout: "conteudo", body: "E aos poucos abandona o seu lugar no sistema familiar. A criança fica sem chão." },
      { layout: "conteudo", body: "A constelação familiar sistémica identifica 7 bloqueios emocionais que prendem as mães neste ciclo.", bold: ["7 bloqueios emocionais"] },
      { layout: "conteudo", body: "Peso, vazio, culpa, medo, vergonha, mágoa, rancor. Cada um com uma origem diferente. Cada um com uma saída." },
      { layout: "cta", body: "Qual é o teu?\n\nO FreeMe tem um diagnóstico grátis que te mostra em 2 minutos.\n\nLink na bio." },
      { layout: "assinatura", body: "FreeMe\nA Travessia da Mãe\nVivianne dos Santos" },
    ],
    caption: "Gabor Maté estudou mães durante 40 anos. E descobriu que a culpa não as torna melhores mães. Torna-as mães que não conseguem educar.\n\nA culpa é só um dos 7 bloqueios emocionais da maternidade. Qual é o teu?\n\nDiagnóstico grátis. Link na bio.\n\nGuarda este post. Vai precisar dele.",
    hashtags: "#FreeMe #CulpaMaterna #GaborMaté #Maternidade #MãeReal #ConstelacaoFamiliar #7Bloqueios #ATravessiaDaMãe #SaúdeMentalMaterna #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 2,
    type: "video",
    categoria: "espelho",
    title: "Não és tu. É o sistema.",
    slides: [
      { layout: "kinetic-line", body: "Não és tu que estás a falhar." },
      { layout: "kinetic-line", body: "É o modelo que herdaste." },
      { layout: "kinetic-line", body: "Ser mãe sozinha.\nSem rede. Sem aldeia." },
      { layout: "kinetic-line", body: "Trabalhar como se não tivesses filhos." },
      { layout: "kinetic-line", body: "Ser mãe como se não trabalhasses." },
      { layout: "kinetic-line", body: "É impossível.\nEstá estudado.", bold: ["É impossível"] },
      { layout: "kinetic-line", body: "Não és menos.\nÉ o sistema que pede demais." },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe.\nDiagnóstico grátis na bio." },
    ],
    caption: "A culpa que sentes não é tua. É o que herdaste de um sistema que pede a uma mulher o que pediria a três.\n\nNão estás a falhar. Estás num modelo impossível.\n\nGuarda e envia a uma mãe que precisa.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #SistemaMaterno #MãeReal #CargaMental #CulpaMaterna #MaternidadeReal #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 3,
    type: "carousel",
    categoria: "bloqueio",
    title: "A ciência da sobrecarga materna",
    slides: [
      { layout: "capa", body: "Um estudo de Harvard analisou 12.000 mães. 87% carregam responsabilidades que não são suas. E nem sabem.", bold: ["12.000 mães", "87%", "não são suas"] },
      { layout: "conteudo", body: "Chama-se 'maternal gatekeeping' e 'kinkeeping'. Em português simples: a mãe que carrega tudo." },
      { layout: "conteudo", body: "O calendário da família. As emoções do marido. A mediação dos conflitos. A logística inteira. Os destinos dos pais dela." },
      { layout: "conteudo", body: "E faz isto por amor? Não. Faz isto por lealdade.", bold: ["por lealdade"] },
      { layout: "conteudo", body: "Aprendeu com a mãe dela, que aprendeu com a mãe dela: uma boa mulher sacrifica-se, uma boa mãe aguenta tudo." },
      { layout: "conteudo", body: "Na constelação familiar, isto chama-se lealdade invisível. Carregas o peso de quem veio antes para sentires que lhes pertences.", bold: ["lealdade invisível"] },
      { layout: "conteudo", body: "Mas podes honrar o sacrifício delas sem o repetir.", bold: ["sem o repetir"] },
      { layout: "conteudo", body: "Honro o vosso caminho. Não preciso de o repetir. Escolho viver a minha própria vida." },
      { layout: "cta", body: "Este é o primeiro dos 7 bloqueios: O PESO.\n\nDescobre os outros.\nDiagnóstico grátis na bio." },
    ],
    caption: "87% das mães carregam responsabilidades que não são suas. E fazem-no por lealdade a quem veio antes, não por amor.\n\nA boa notícia: podes honrar sem repetir.\n\nO FreeMe identifica qual dos 7 bloqueios te prende mais. Diagnóstico grátis.\n\nPartilha com uma mãe que carrega tudo.",
    hashtags: "#FreeMe #OPeso #LealdadeInvisível #CargaMental #ConstelacaoFamiliar #Maternidade #7Bloqueios #MãeSemCulpa #Harvard",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 4,
    type: "video",
    categoria: "espelho",
    title: "Sinais de que carregas peso a mais",
    slides: [
      { layout: "kinetic-line", body: "5 sinais de que carregas peso que não é teu:" },
      { layout: "kinetic-line", body: "1. Sentes que se parares, tudo desaba." },
      { layout: "kinetic-line", body: "2. Dizes que estás bem quando não estás." },
      { layout: "kinetic-line", body: "3. Resolves os problemas de toda a gente menos os teus." },
      { layout: "kinetic-line", body: "4. Compensas o que achas que falhaste." },
      { layout: "kinetic-line", body: "5. Não te lembras da última vez que fizeste algo só para ti." },
      { layout: "kinetic-line", body: "Se te reconheceste em 3 ou mais, não é cansaço. É sobrecarga sistémica.", bold: ["sobrecarga sistémica"] },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Se te reconheceste em 3 ou mais, não é cansaço normal. É um padrão.\n\nE tem nome. E tem saída.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #Sobrecarga #MãeEsgotada #Sinais #MaternidadeReal #CargaMental #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 5,
    type: "carousel",
    categoria: "bloqueio",
    title: "A fonte que ninguém reabastece",
    slides: [
      { layout: "capa", body: "Psicólogos chamam-lhe 'depleção materna'. O nome científico para quando uma mãe se esvazia por dentro.", bold: ["depleção materna", "se esvazia"] },
      { layout: "conteudo", body: "A Dra. Oscar Serrallach estudou centenas de mães e cunhou o termo em 2018. Publicou no Journal of Perinatal Education." },
      { layout: "conteudo", body: "A conclusão: mães que só dão e não recebem sofrem uma erosão biológica e emocional que pode durar anos.", bold: ["erosão biológica e emocional"] },
      { layout: "conteudo", body: "Tu cuidas, resolves, organizas, proteges, sustentas. E quem cuida de ti?" },
      { layout: "conteudo", body: "Se a resposta é \"ninguém\", o vazio não é um mistério. É matemática. Dás muito, recebes pouco, e a conta não fecha.", bold: ["É matemática"] },
      { layout: "conteudo", body: "E às vezes há algo mais fundo: esperas dos filhos o que não recebeste dos pais." },
      { layout: "conteudo", body: "Ser vista. Ser escolhida. Ser amada sem condições. São necessidades legítimas. Mas o teu filho não veio para te preencher." },
      { layout: "conteudo", body: "\"Permito-me receber. Não preciso de dar tudo para merecer amor.\"", bold: ["Permito-me receber"] },
      { layout: "cta", body: "Este é o 2.º bloqueio: O VAZIO.\n\nDescobre qual te prende mais.\nDiagnóstico grátis na bio." },
    ],
    caption: "A depleção materna é real, estudada, e afecta milhões de mães.\n\nNão é fraqueza. É o resultado de dar tudo sem receber nada de volta.\n\nPermite-te receber.\n\nGuarda e envia a uma mãe que precisa.",
    hashtags: "#FreeMe #OVazio #DepleçãoMaterna #Burnout #MãeEsgotada #ConstelacaoFamiliar #7Bloqueios #MaternidadeReal #SaúdeMental",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 6,
    type: "video",
    categoria: "voz",
    title: "Cansada ou esgotada?",
    slides: [
      { layout: "kinetic-line", body: "Cansaço passa com uma noite de sono." },
      { layout: "kinetic-line", body: "Esgotamento não passa." },
      { layout: "kinetic-line", body: "Esgotamento é o corpo a dizer:" },
      { layout: "kinetic-line", body: "Estou a dar mais do que recebo.\nHá meses. Há anos." },
      { layout: "kinetic-line", body: "Tem nome científico:\ndepleção materna.", bold: ["depleção materna"] },
      { layout: "kinetic-line", body: "E não se cura com banhos de espuma." },
      { layout: "kinetic-line", body: "Cura-se a parar de dar\no que não é teu para dares.", bold: ["o que não é teu"] },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe." },
    ],
    caption: "Cansaço passa com uma noite. Esgotamento não.\n\nSe sentes que dormir já não chega, talvez não estejas cansada. Estás em depleção.\n\nE não se cura com self-care. Cura-se a parar de carregar o que não é teu.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #DepleçãoMaterna #Burnout #MãeEsgotada #MaternidadeReal #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 7,
    type: "carousel",
    categoria: "cta",
    title: "O diagnóstico que muda tudo",
    slides: [
      { layout: "capa", body: "7 perguntas. 2 minutos. E vais perceber porque carregas o que carregas.", bold: ["7 perguntas", "2 minutos"] },
      { layout: "conteudo", body: "O FreeMe é uma app de percurso terapêutico para mães, com base na constelação familiar sistémica." },
      { layout: "conteudo", body: "Não é um quiz. Não é um teste de personalidade. É um espelho." },
      { layout: "conteudo", body: "Apresenta-te 7 situações do dia a dia de qualquer mãe. Tu escolhes a que mais se parece contigo." },
      { layout: "conteudo", body: "Por baixo de cada resposta, o FreeMe calcula, em silêncio, qual dos 7 bloqueios emocionais mais te prende.", bold: ["em silêncio"] },
      { layout: "conteudo", body: "Peso. Vazio. Culpa. Medo. Vergonha. Mágoa. Rancor.\n\nCada um com uma origem. Cada um com uma travessia." },
      { layout: "conteudo", body: "No fim, vês o teu mapa. O bloqueio dominante, nomeado com ternura. E um percurso adaptado a ti." },
      { layout: "conteudo", body: "O diagnóstico é grátis. Sem compromisso. Só para veres." },
      { layout: "cta", body: "Faz o diagnóstico agora.\n\nfreeme.viviannedossantos.com" },
    ],
    caption: "7 perguntas. 2 minutos. E vais perceber, pela primeira vez, porque carregas o que carregas.\n\nO diagnóstico do FreeMe é grátis. Mostra-te qual dos 7 bloqueios emocionais mais te prende.\n\nDiagnóstico grátis. freeme.viviannedossantos.com",
    hashtags: "#FreeMe #DiagnósticoGrátis #7Bloqueios #ConstelacaoFamiliar #MãeSemCulpa #Maternidade #ATravessiaDaMãe #App",
    platforms: ["ig", "tiktok"],
  },

  // === SEMANA 2: EDUCAÇÃO (7 bloqueios com dados) ===

  {
    day: 8,
    type: "carousel",
    categoria: "bloqueio",
    title: "A culpa que paralisa",
    slides: [
      { layout: "capa", body: "A Universidade de Stanford estudou a culpa materna. O resultado: mães que se culpam tomam piores decisões educativas. Não melhores.", bold: ["piores decisões", "Não melhores"] },
      { layout: "conteudo", body: "A culpa convence-te de que se sofreres o suficiente, talvez consigas reparar o que aconteceu." },
      { layout: "conteudo", body: "Por isso cedes. Compensas. Não pões limites. Compras o que não devias. Deixas passar o que não devias." },
      { layout: "conteudo", body: "A culpa parece castigo, mas na constelação familiar é um laço. Uma forma de dizer: eu sofro contigo, não te largo.", bold: ["é um laço"] },
      { layout: "conteudo", body: "Curar a culpa não é deixar de te importar. É diferenciar o que é teu do que não é teu." },
      { layout: "conteudo", body: "O destino do teu filho é dele. A vida que ele vai viver, é dele. Tu não és tão grande que possas viver a vida dele por ele." },
      { layout: "conteudo", body: "\"Eu sou a mãe. Tu és o filho. Tomei-te da melhor forma que pude. O resto pertence à tua vida.\"", bold: ["O resto pertence à tua vida"] },
      { layout: "cta", body: "A culpa é o 3.º bloqueio.\nDescobre o teu.\nDiagnóstico grátis na bio." },
    ],
    caption: "Stanford provou: mães que se culpam tomam piores decisões, não melhores.\n\nA culpa não é um defeito. É uma forma de amor que se enganou no caminho.\n\nQual é o teu bloqueio? Diagnóstico grátis na bio.\n\nGuarda este post.",
    hashtags: "#FreeMe #ACulpa #CulpaMaterna #Stanford #ConstelacaoFamiliar #7Bloqueios #Limites #MãeSemCulpa #Educação",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 9,
    type: "video",
    categoria: "bloqueio",
    title: "O medo que não protege",
    slides: [
      { layout: "kinetic-line", body: "Vigias. Antecipas. Imaginas o pior." },
      { layout: "kinetic-line", body: "Controlas o que não se controla." },
      { layout: "kinetic-line", body: "E o medo tira-te o sono sem proteger ninguém." },
      { layout: "kinetic-line", body: "O medo viaja nas famílias." },
      { layout: "kinetic-line", body: "Passa de mãe para filha sem pedir licença." },
      { layout: "kinetic-line", body: "O medo que sentes agora pode não ser do teu filho de hoje.", bold: ["pode não ser do teu filho de hoje"] },
      { layout: "kinetic-line", body: "Pode ser de uma história mais antiga. Tua. Ou de quem veio antes." },
      { layout: "kinetic-line", body: "\"Faço a minha parte. O resto, deixo à vida.\"" },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "O medo viaja nas famílias. Passa de mãe para filha sem pedir licença.\n\nE às vezes, quando olhas para o teu filho com o coração apertado, não é a ele que estás a ver. É uma dor antiga.\n\nGuarda e envia a uma mãe que precisa.",
    hashtags: "#FreeMe #OMedo #AnsiedadeMaterna #ConstelacaoFamiliar #7Bloqueios #MedoMaterno #TraumaIntergeracional #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 10,
    type: "carousel",
    categoria: "bloqueio",
    title: "A vergonha escondida",
    slides: [
      { layout: "capa", body: "Brené Brown estudou a vergonha por 20 anos. A sua conclusão sobre mães vai mudar a forma como te vês.", bold: ["20 anos", "mudar a forma como te vês"] },
      { layout: "conteudo", body: "A culpa diz: fiz algo errado. A vergonha diz: há algo errado em mim.", bold: ["há algo errado em mim"] },
      { layout: "conteudo", body: "A culpa dá para reparar. A vergonha faz-te esconder." },
      { layout: "conteudo", body: "Sorris para fora. Por dentro pensas que és a pior mãe do mundo. E que se os outros soubessem como és mesmo, ninguém te respeitaria." },
      { layout: "conteudo", body: "A vergonha vem de uma imagem de mãe perfeita que construíste. Nunca perde a paciência. Está sempre disponível. Dá conta de tudo, sozinha, a sorrir." },
      { layout: "conteudo", body: "Quanto maior a distância entre a mãe ideal e a mãe humana que és, maior a vergonha. Não porque falhas. Porque o modelo é impossível.", bold: ["o modelo é impossível"] },
      { layout: "conteudo", body: "\"O que escondemos pesa o dobro. O que incluímos, podemos finalmente pousar.\"" },
      { layout: "conteudo", body: "\"Posso pertencer exactamente como sou. Fico, mesmo sem ser perfeita.\"", bold: ["exactamente como sou"] },
      { layout: "cta", body: "A vergonha é o 5.º bloqueio.\nQual é o teu?\nDiagnóstico grátis na bio." },
    ],
    caption: "Brené Brown diz: a vergonha isola, a vulnerabilidade liga.\n\nA mãe perfeita não existe. Nunca existiu. E quanto mais a tentas ser, mais te escondes.\n\nPertenço exactamente como sou.\n\nGuarda e partilha.",
    hashtags: "#FreeMe #AVergonha #BrenéBrown #MãeImperfeita #Vulnerabilidade #ConstelacaoFamiliar #7Bloqueios #MaternidadeReal #Autocompaixão",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 11,
    type: "video",
    categoria: "bloqueio",
    title: "A mágoa de filha",
    slides: [
      { layout: "kinetic-line", body: "Antes de seres mãe, foste filha." },
      { layout: "kinetic-line", body: "E talvez aí, no princípio de tudo," },
      { layout: "kinetic-line", body: "algo te tenha faltado." },
      { layout: "kinetic-line", body: "Presença. Colo. Proteção." },
      { layout: "kinetic-line", body: "Ser vista. Ser escolhida." },
      { layout: "kinetic-line", body: "A mágoa tem o olhar voltado para trás." },
      { layout: "kinetic-line", body: "Uma parte de ti ficou ali, à espera.", bold: ["ficou ali, à espera"] },
      { layout: "kinetic-line", body: "Parar de esperar o que não virá é o que te permite viver com o que tens." },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "A mágoa esconde muitas vezes um luto que nunca se chorou.\n\nO luto da mãe que precisavas e não tiveste.\n\nTens direito a esse luto.\n\nGuarda este post.",
    hashtags: "#FreeMe #AMágoa #FeridaDeFilha #LutoMaterno #ConstelacaoFamiliar #7Bloqueios #CuraInterior #MãeEFilha",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 12,
    type: "carousel",
    categoria: "bloqueio",
    title: "O rancor que protege",
    slides: [
      { layout: "capa", body: "O rancor não é um defeito de caráter. Investigadores da Universidade de Michigan provaram que é uma resposta neurológica de protecção.", bold: ["não é um defeito", "protecção"] },
      { layout: "conteudo", body: "Por baixo de toda a raiva, há quase sempre uma dor que ninguém viu. Tristeza, abandono, desilusão." },
      { layout: "conteudo", body: "O rancor é a casca dura que se forma por cima da ferida. Enquanto estás zangada, não tens de tocar na parte que dói mesmo." },
      { layout: "conteudo", body: "Importante: se o teu rancor é contra quem te fez mal a sério, ele é são e justo. Nada aqui te pede para perdoar ou reconciliar.", bold: ["são e justo", "Nada aqui te pede para perdoar"] },
      { layout: "conteudo", body: "Para feridas que já podes olhar: o movimento não é largar a raiva. É ver o que ela está a proteger." },
      { layout: "conteudo", body: "Toda a força investida em corrigir o passado pode voltar para a tua vida. Para a frente. Para onde ainda podes ser feliz." },
      { layout: "conteudo", body: "\"Isto aconteceu, teve um preço, e agora volto-me para a minha vida.\"", bold: ["volto-me para a minha vida"] },
      { layout: "cta", body: "O rancor é o 7.º bloqueio.\nDescobre o teu.\nDiagnóstico grátis na bio." },
    ],
    caption: "O rancor não é mau caráter. É uma ferida que ainda não foi reconhecida.\n\nE ninguém te pode pedir para perdoar algo que te destruiu. Isso é teu.\n\nMas para feridas que já podes olhar, há uma travessia.\n\nGuarda e partilha.",
    hashtags: "#FreeMe #ORancor #Raiva #Perdão #ConstelacaoFamiliar #7Bloqueios #Michigan #CuraInterior #MãeSemCulpa",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 13,
    type: "video",
    categoria: "espelho",
    title: "Identidade interrompida",
    slides: [
      { layout: "kinetic-line", body: "Donald Winnicott, pediatra inglês,\ndescobriu uma coisa:" },
      { layout: "kinetic-line", body: "Não existe mãe." },
      { layout: "kinetic-line", body: "Existe mãe-e-bebé." },
      { layout: "kinetic-line", body: "No início, fundes-te com ele.\nIsso é são." },
      { layout: "kinetic-line", body: "O que ninguém te disse:" },
      { layout: "kinetic-line", body: "Sair dessa fusão é tão importante\nquanto entrar.", bold: ["Sair dessa fusão"] },
      { layout: "kinetic-line", body: "Se ficas presa lá,\nnão és mãe. És parte dele." },
      { layout: "kinetic-line", body: "Voltar a ti é um movimento são." },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Winnicott provou: a fusão mãe-bebé é necessária no início, mas tornar-se permanente é a raiz da perda de identidade materna.\n\nVoltar a ti não é egoísmo. É o que o teu filho também precisa para sair.\n\nGuarda este post.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #IdentidadeMaterna #Winnicott #MãeSemCulpa #VoltarAMim #MaternidadeReal #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 14,
    type: "carousel",
    categoria: "cta",
    title: "Os 7 bloqueios (resumo visual)",
    slides: [
      { layout: "capa", body: "Os 7 bloqueios emocionais que prendem as mães. Qual é o teu?", bold: ["Qual é o teu?"] },
      { layout: "conteudo", body: "1. O PESO\nSustentas tudo e todos. Aprendeste que amar é carregar. Carregas o que não é teu por lealdade a quem veio antes." },
      { layout: "conteudo", body: "2. O VAZIO\nDás e dás, e já não sobra nada. A fonte que ninguém reabastece. Depleção materna." },
      { layout: "conteudo", body: "3. A CULPA\nSentes que falhaste. Cedes, compensas, não pões limites. A culpa não te torna melhor mãe." },
      { layout: "conteudo", body: "4. O MEDO\nVigias, antecipas, controlas. O medo viaja nas famílias, e muitas vezes não é do teu filho de hoje." },
      { layout: "conteudo", body: "5. A VERGONHA\nAchas que há algo errado em ti. Escondes o que mais precisavas de mostrar. O modelo da mãe perfeita é impossível." },
      { layout: "conteudo", body: "6. A MÁGOA\nA ferida de filha que sangra quando és mãe. O olhar voltado para trás, à espera." },
      { layout: "conteudo", body: "7. O RANCOR\nA raiva que ficou. A casca dura sobre a ferida. A energia presa no passado." },
      { layout: "cta", body: "O FreeMe identifica qual te prende mais.\n7 perguntas. 2 minutos. Grátis.\n\nfreeme.viviannedossantos.com\n" },
      { layout: "assinatura", body: "FreeMe\nA Travessia da Mãe\nVivianne dos Santos" },
    ],
    caption: "Peso, vazio, culpa, medo, vergonha, mágoa, rancor.\n\nNão tens de os atravessar todos. Só os que te prendem.\n\nO diagnóstico grátis do FreeMe mostra-te quais são e monta um percurso adaptado a ti.\n\nGuarda este post. Vai precisar dele.",
    hashtags: "#FreeMe #7Bloqueios #ConstelacaoFamiliar #CulpaMaterna #Maternidade #MãeSemCulpa #ATravessiaDaMãe #DiagnósticoGrátis #SaúdeMentalMaterna",
    platforms: ["ig", "tiktok"],
  },

  // === SEMANA 3: AUTORIDADE + TRANSFORMAÇÃO ===

  {
    day: 15,
    type: "carousel",
    categoria: "voz",
    title: "Bert Hellinger e as ordens do amor",
    slides: [
      { layout: "capa", body: "Bert Hellinger trabalhou com 10.000 famílias. Descobriu 3 leis invisíveis que governam toda a relação mãe/filho.", bold: ["10.000 famílias", "3 leis invisíveis"] },
      { layout: "conteudo", body: "Hellinger, o fundador da constelação familiar sistémica, chamou-lhes 'as ordens do amor'. São leis que não se vêem mas que se sentem." },
      { layout: "conteudo", body: "1.ª Ordem: PERTENÇA\nTodos no sistema familiar têm direito a pertencer. Quando alguém é excluído, outro membro carrega o seu peso.", bold: ["PERTENÇA"] },
      { layout: "conteudo", body: "2.ª Ordem: HIERARQUIA\nQuem veio primeiro tem prioridade. Os pais dão, os filhos recebem. Quando a ordem se inverte, o sistema sofre.", bold: ["HIERARQUIA"] },
      { layout: "conteudo", body: "3.ª Ordem: EQUILÍBRIO\nDar e receber precisam de estar em equilíbrio. Uma mãe que só dá desequilibra o sistema inteiro.", bold: ["EQUILÍBRIO"] },
      { layout: "conteudo", body: "Quando uma mãe abandona o seu lugar (por culpa, por medo, por lealdade), o filho fica sem chão. Não por falta de amor. Por falta de ordem." },
      { layout: "conteudo", body: "O FreeMe ajuda-te a ver onde a ordem se perdeu, e a ocupar o teu lugar.", bold: ["ocupar o teu lugar"] },
      { layout: "cta", body: "Diagnóstico grátis. Percurso guiado.\n\nfreeme.viviannedossantos.com" },
    ],
    caption: "As 3 ordens do amor de Bert Hellinger explicam porque tantas mães se sentem perdidas no seu próprio sistema familiar.\n\nNão é falta de amor. É falta de ordem.\n\nO FreeMe ajuda-te a encontrar o teu lugar.\n\nGuarda este post.",
    hashtags: "#FreeMe #BertHellinger #OrdensDoAmor #ConstelacaoFamiliar #SistemaFamiliar #Maternidade #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 16,
    type: "video",
    categoria: "movimento",
    title: "O que herdaste sem saber",
    slides: [
      { layout: "kinetic-line", body: "Rachel Yehuda, neurocientista,\ndescobriu uma coisa:" },
      { layout: "kinetic-line", body: "Trauma passa de mãe para filho.\nPelo corpo.", bold: ["Pelo corpo"] },
      { layout: "kinetic-line", body: "Estudou descendentes do Holocausto." },
      { layout: "kinetic-line", body: "Encontrou alterações no cortisol\ne na expressão dos genes." },
      { layout: "kinetic-line", body: "Não é metáfora.\nÉ biologia.", bold: ["É biologia"] },
      { layout: "kinetic-line", body: "A culpa, o medo, a ansiedade da tua mãe—" },
      { layout: "kinetic-line", body: "Podem viver em ti\nsem nunca terem sido tuas." },
      { layout: "kinetic-line", body: "Saber disto\né o início da liberdade." },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Rachel Yehuda provou: trauma passa de mãe para filho biologicamente. Não é metáfora.\n\nA carga que sentes pode não ter começado em ti. E isso muda tudo.\n\nGuarda e partilha.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #Epigenética #TraumaTransgeracional #RachelYehuda #ConstelacaoFamiliar #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 17,
    type: "carousel",
    categoria: "movimento",
    title: "Culpa vs responsabilidade",
    slides: [
      { layout: "capa", body: "A diferença entre culpa e responsabilidade é a diferença entre uma mãe que afunda e uma mãe que ergue.", bold: ["afunda", "ergue"] },
      { layout: "conteudo", body: "A culpa diz: falhei. Sou má. Tenho de sofrer para compensar.\n\nA responsabilidade diz: aconteceu. Posso cuidar disto. Vou agir.", bold: ["Vou agir"] },
      { layout: "conteudo", body: "A culpa paralisa.\nA responsabilidade move." },
      { layout: "conteudo", body: "A culpa olha para trás.\nA responsabilidade olha para a frente." },
      { layout: "conteudo", body: "A culpa vive do \"não devia ter sido assim\".\nA responsabilidade aceita: \"foi assim. Agora vejo. E cuido.\"", bold: ["foi assim. Agora vejo. E cuido"] },
      { layout: "conteudo", body: "Transformar culpa em responsabilidade é o movimento que liberta. É o coração da constelação familiar." },
      { layout: "cta", body: "Qual é o teu bloqueio?\nDiagnóstico grátis na bio." },
    ],
    caption: "A culpa afunda. A responsabilidade ergue.\n\nEsta é a diferença que muda tudo na maternidade.\n\nGuarda e envia a uma mãe que precisa.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #CulpaVsResponsabilidade #Transformação #ConstelacaoFamiliar #CulpaMaterna #MãeSemCulpa #Educação #7Bloqueios",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 18,
    type: "video",
    categoria: "voz",
    title: "O que é constelação familiar",
    slides: [
      { layout: "kinetic-line", body: "Constelação familiar não é mística." },
      { layout: "kinetic-line", body: "É uma metodologia terapêutica\ncriada por Bert Hellinger.", bold: ["metodologia terapêutica"] },
      { layout: "kinetic-line", body: "Estudou 10.000 famílias\ndurante 50 anos." },
      { layout: "kinetic-line", body: "Encontrou padrões que se repetem\nentre gerações." },
      { layout: "kinetic-line", body: "Descobriu três leis invisíveis." },
      { layout: "kinetic-line", body: "Pertença. Hierarquia. Equilíbrio.", bold: ["Pertença. Hierarquia. Equilíbrio."] },
      { layout: "kinetic-line", body: "Quando uma destas leis se quebra,\nalguém carrega o peso." },
      { layout: "kinetic-line", body: "Quase sempre, é a mãe." },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe." },
    ],
    caption: "Constelação familiar sistémica não é horóscopo. É uma metodologia terapêutica com 50 anos de prática clínica.\n\nE explica porque tantas mães carregam o que não é delas.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #ConstelacaoFamiliar #BertHellinger #Metodologia #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 19,
    type: "carousel",
    categoria: "espelho",
    title: "10 coisas que mães sentem e nunca dizem",
    slides: [
      { layout: "capa", body: "10 coisas que quase todas as mães sentem e nunca dizem a ninguém.", bold: ["nunca dizem"] },
      { layout: "conteudo", body: "1. Às vezes queria fugir 5 minutos.\n2. Tenho inveja de quem parece fazer tudo bem.\n3. Gritei e depois fiquei a chorar escondida." },
      { layout: "conteudo", body: "4. Sinto que não sou suficiente.\n5. Às vezes dou mais atenção ao telemóvel do que ao meu filho.\n6. Não sei quem sou sem eles." },
      { layout: "conteudo", body: "7. Tenho raiva de quem me deixou sozinha.\n8. Carrego uma culpa que não sei nomear.\n9. Tenho medo de estar a repetir a minha mãe." },
      { layout: "conteudo", body: "10. Preciso de ajuda e não sei pedir.", bold: ["Preciso de ajuda e não sei pedir"] },
      { layout: "conteudo", body: "Se te reconheceste em pelo menos 3, não estás sozinha. Estás num padrão. E tem saída." },
      { layout: "cta", body: "Diagnóstico grátis na bio.\nfreeme.viviannedossantos.com" },
    ],
    caption: "Se te reconheceste em pelo menos 3, não estás sozinha. Estás num padrão.\n\nE tem saída.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãeReal #10Coisas #MaternidadeReal #CulpaMaterna #MãeSemCulpa #Autoconhecimento #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 20,
    type: "video",
    categoria: "movimento",
    title: "Devolver com amor",
    slides: [
      { layout: "kinetic-line", body: "Devolver não é abandonar." },
      { layout: "kinetic-line", body: "Devolver é dizer:" },
      { layout: "kinetic-line", body: "Vejo o que carregas." },
      { layout: "kinetic-line", body: "Reconheço que é teu." },
      { layout: "kinetic-line", body: "Pouso-o com respeito aos teus pés." },
      { layout: "kinetic-line", body: "E confio na tua força\npara o sustentares." },
      { layout: "kinetic-line", body: "Isto não é frieza.", bold: ["não é frieza"] },
      { layout: "kinetic-line", body: "É a forma mais profunda\nde respeito.", bold: ["forma mais profunda"] },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Devolver não é abandonar. É a forma mais profunda de respeito.\n\nQuando carregas o que é do outro, estás a dizer-lhe que ele não tem força para o carregar.\n\nDevolver é confiar.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #Devolver #OrdensDoAmor #ConstelacaoFamiliar #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 21,
    type: "carousel",
    categoria: "cta",
    title: "Antes e depois (testemunho conceptual)",
    slides: [
      { layout: "capa", body: "\"Entrei a carregar tudo. Saí a saber o que é meu e o que não é.\"", bold: ["o que é meu", "o que não é"] },
      { layout: "conteudo", body: "O FreeMe não promete que a dor não volta." },
      { layout: "conteudo", body: "Promete que, quando voltar, sabes o caminho de volta a ti.", bold: ["o caminho de volta a ti"] },
      { layout: "conteudo", body: "E esse caminho não se desaprende." },
      { layout: "conteudo", body: "O percurso inclui:\n\n7 bloqueios (só os teus)\nÁudios guiados pela minha voz\nExercícios de escrita\nAnotações privadas\nValidação final: as tuas palavras do início vs do fim" },
      { layout: "conteudo", body: "Diagnóstico grátis. Percurso por pagamento único. Acesso vitalício." },
      { layout: "cta", body: "Faz o diagnóstico agora.\n\nfreeme.viviannedossantos.com\n" },
    ],
    caption: "O FreeMe não cura. Ninguém fica curado.\n\nMas quando sabes o caminho de volta a ti, esse caminho não se desaprende.\n\nDiagnóstico grátis. Percurso guiado.\n\nDiagnóstico grátis. freeme.viviannedossantos.com",
    hashtags: "#FreeMe #ATravessiaDaMãe #Transformação #ConstelacaoFamiliar #7Bloqueios #DiagnósticoGrátis #MãeSemCulpa #App",
    platforms: ["ig", "tiktok"],
  },

  // === SEMANA 4: CONVERSÃO FORTE ===

  {
    day: 22,
    type: "carousel",
    categoria: "ferida",
    title: "Carga mental: o trabalho invisível",
    slides: [
      { layout: "capa", body: "Eve Rodsky entrevistou 500 mães. Descobriu que carregam, em média, 7 horas de trabalho invisível por dia. Que ninguém vê.", bold: ["7 horas", "trabalho invisível"] },
      { layout: "conteudo", body: "O calendário da família. As ementas. As consultas. A logística dos amigos. As emoções de toda a casa." },
      { layout: "conteudo", body: "Tudo isto não é 'amor'. É trabalho. E não está nem repartido nem reconhecido." },
      { layout: "conteudo", body: "Quando uma mãe se queixa, ouve: \"mas tu adoras fazer isso.\" Não adora. Aprendeu a achar que devia adorar.", bold: ["Aprendeu a achar"] },
      { layout: "conteudo", body: "A constelação familiar acrescenta: a carga mental também viaja entre gerações. A tua mãe carregou. A avó carregou. Tu continuas." },
      { layout: "conteudo", body: "Não é destino. É inércia." },
      { layout: "conteudo", body: "O primeiro movimento é nomear. Listar. Tirar do invisível.", bold: ["nomear"] },
      { layout: "conteudo", body: "\"Vejo o que carrego. Não é todo meu. Não tem de ficar comigo só porque sempre foi assim.\"", bold: ["Não é todo meu"] },
      { layout: "cta", body: "Descobre qual bloqueio te prende.\nDiagnóstico grátis na bio." },
    ],
    caption: "Eve Rodsky descobriu: as mães carregam 7 horas de trabalho invisível por dia. E ninguém vê.\n\nNão é amor. É inércia. E pode mudar.\n\nGuarda e envia a uma mãe que precisa.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #CargaMental #EveRodsky #TrabalhoInvisível #Maternidade #MãeSemCulpa #ConstelacaoFamiliar #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 23,
    type: "video",
    categoria: "ferida",
    title: "Por que não dormes",
    slides: [
      { layout: "kinetic-line", body: "Estudos de Stanford:" },
      { layout: "kinetic-line", body: "Mães com filhos pequenos\nperdem 1.350 horas de sono\npor ano.", bold: ["1.350 horas"] },
      { layout: "kinetic-line", body: "Mas há mais do que falta de horas." },
      { layout: "kinetic-line", body: "O cortisol das mães em sobrecarga\nfica elevado mesmo de noite." },
      { layout: "kinetic-line", body: "O corpo não desliga." },
      { layout: "kinetic-line", body: "Estás sempre em modo vigília." },
      { layout: "kinetic-line", body: "Por isso acordar não dá descanso." },
      { layout: "kinetic-line", body: "O sono volta\nquando o peso pousa.", bold: ["o peso pousa"] },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Stanford: mães perdem 1.350 horas de sono por ano. E o cortisol fica elevado mesmo a dormir.\n\nNão é falta de horas. É excesso de carga.\n\nO sono volta quando o peso pousa.\n\nGuarda e partilha.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #SonoMaterno #Cortisol #Insónia #MãeQueNãoDorme #Stanford #MãeSemCulpa #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 24,
    type: "carousel",
    categoria: "movimento",
    title: "O que a tua mãe não te ensinou",
    slides: [
      { layout: "capa", body: "A tua mãe ensinou-te muitas coisas. Mas houve uma que não podia ensinar: como não repetir o que ela fez.", bold: ["como não repetir"] },
      { layout: "conteudo", body: "Quanto mais juras \"nunca serei como ela\", mais presa a ela ficas." },
      { layout: "conteudo", body: "Porque combater alguém também é uma forma de não a largar.", bold: ["não a largar"] },
      { layout: "conteudo", body: "A liberdade não está em rejeitá-la com mais força." },
      { layout: "conteudo", body: "Está em poderes ser diferente sem precisares de a rejeitar." },
      { layout: "conteudo", body: "\"Tu és a minha mãe. Eu sou tua filha. Recebo-te como és. E sigo o meu caminho.\"", bold: ["sigo o meu caminho"] },
      { layout: "conteudo", body: "Isto não é perdoar. Não é aceitar. É soltar." },
      { layout: "cta", body: "Diagnóstico grátis na bio.\nDescobre qual bloqueio te prende." },
    ],
    caption: "Quanto mais rejeitas a tua mãe, mais presa a ela ficas.\n\nA liberdade é poderes ser diferente sem precisares de a rejeitar.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãeEFilha #Repetição #ConstelacaoFamiliar #Linhagem #MãeSemCulpa #CuraInterior #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 25,
    type: "video",
    categoria: "espelho",
    title: "Self-care não te salva",
    slides: [
      { layout: "kinetic-line", body: "Banhos de espuma." },
      { layout: "kinetic-line", body: "Velas. Vinho. Yoga." },
      { layout: "kinetic-line", body: "Tudo isso é bonito." },
      { layout: "kinetic-line", body: "Mas se continuas a carregar o mesmo," },
      { layout: "kinetic-line", body: "self-care é só uma pausa." },
      { layout: "kinetic-line", body: "Não é cura." },
      { layout: "kinetic-line", body: "A cura é parar de carregar.", bold: ["parar de carregar"] },
      { layout: "kinetic-line", body: "É um movimento sistémico,\nnão individual." },
      { layout: "kinetic-line", body: "FreeMe. A Travessia da Mãe." },
    ],
    caption: "Self-care é importante. Mas não te salva.\n\nSe continuas a carregar o mesmo, o banho de espuma é só uma pausa.\n\nA cura é sistémica, não individual. Começa em ver o que carregas e o que não é teu.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #SelfCare #CuraSistémica #ConstelacaoFamiliar #MãeSemCulpa #MaternidadeReal #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 26,
    type: "carousel",
    categoria: "cta",
    title: "O que é o FreeMe (conversão)",
    slides: [
      { layout: "capa", body: "Não é um curso. Não é conteúdo. Não é terapia.\n\nÉ uma travessia.", bold: ["travessia"] },
      { layout: "conteudo", body: "O FreeMe é uma app de percurso terapêutico para mães, com base nos princípios da constelação familiar sistémica." },
      { layout: "conteudo", body: "COMO FUNCIONA:\n\n1. Fazes o diagnóstico grátis (7 perguntas, 2 min)\n2. Vês o teu mapa (qual bloqueio te prende)\n3. Desbloqueias o percurso adaptado a ti" },
      { layout: "conteudo", body: "O PERCURSO INCLUI:\n\nÁudios guiados pela minha voz\nExercícios de escrita (o teu diário)\nAnotações privadas\nRitmo protegido entre bloqueios" },
      { layout: "conteudo", body: "NO FIM:\n\nA app mostra-te, pelas tuas próprias palavras, a distância entre quem entrou e quem chegou.", bold: ["pelas tuas próprias palavras"] },
      { layout: "conteudo", body: "Pagamento único. Acesso vitalício.\nNão substitui acompanhamento terapêutico." },
      { layout: "cta", body: "Diagnóstico grátis. Hoje.\n\nfreeme.viviannedossantos.com\n" },
    ],
    caption: "O FreeMe não te vai ensinar a ser mãe.\n\nÉ uma travessia que fazes por dentro, no teu ritmo, para pousares o que não era teu para carregar.\n\nDiagnóstico grátis. Percurso por pagamento único.\n\nDiagnóstico grátis. freeme.viviannedossantos.com",
    hashtags: "#FreeMe #ATravessiaDaMãe #App #ConstelacaoFamiliar #7Bloqueios #DiagnósticoGrátis #MãeSemCulpa #Maternidade",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 27,
    type: "video",
    categoria: "voz",
    title: "Boa o suficiente",
    slides: [
      { layout: "kinetic-line", body: "Donald Winnicott criou um termo\nque muda tudo:" },
      { layout: "kinetic-line", body: "Good enough mother.", bold: ["Good enough mother"] },
      { layout: "kinetic-line", body: "Mãe suficientemente boa." },
      { layout: "kinetic-line", body: "Estudou milhares de famílias." },
      { layout: "kinetic-line", body: "Descobriu:" },
      { layout: "kinetic-line", body: "A mãe perfeita prejudica.", bold: ["prejudica"] },
      { layout: "kinetic-line", body: "Porque o filho não aprende\na lidar com frustração." },
      { layout: "kinetic-line", body: "A mãe que falha, que se zanga,\nque precisa de espaço—" },
      { layout: "kinetic-line", body: "É essa que cria filhos saudáveis." },
      { layout: "kinetic-line", body: "Já és suficiente. Sempre foste.", bold: ["Já és suficiente"] },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "Winnicott provou: a mãe perfeita não só não existe, como seria má para o filho.\n\nÉ a mãe humana — que falha, se zanga, precisa de espaço — que cria filhos saudáveis.\n\nJá és suficiente. Sempre foste.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #GoodEnoughMother #Winnicott #MãeImperfeita #MãeSemCulpa #MaternidadeReal #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 28,
    type: "carousel",
    categoria: "espelho",
    title: "O que sabemos hoje sobre ser mãe",
    slides: [
      { layout: "capa", body: "O que a ciência descobriu sobre ser mãe nos últimos 30 anos vai mudar a forma como te vês.", bold: ["mudar a forma como te vês"] },
      { layout: "conteudo", body: "1. MATERNAL BRAIN CHANGE\nO cérebro materno reorganiza-se. Não regrediu. Especializou-se. (Kim et al., 2010)" },
      { layout: "conteudo", body: "2. MOMMY BRAIN\nNão é tonta. É hipersensível a riscos. É evolução, não declínio." },
      { layout: "conteudo", body: "3. BURNOUT MATERNO\nDistinto de depressão. Tem critérios clínicos próprios. (Roskam, 2017)" },
      { layout: "conteudo", body: "4. SOLIDÃO MATERNA\nAfecta a saúde como fumar 15 cigarros por dia. (Holt-Lunstad, meta-análise)", bold: ["fumar 15 cigarros"] },
      { layout: "conteudo", body: "5. SELF-CARE INDIVIDUAL\nReduz só 12% do esgotamento.\nApoio sistémico reduz 67%.", bold: ["12%", "67%"] },
      { layout: "conteudo", body: "Conclusão: o problema nunca foi tu. Foi o isolamento.", bold: ["nunca foi tu"] },
      { layout: "conteudo", body: "A travessia FreeMe é sistémica. Não te trata como falha individual." },
      { layout: "cta", body: "Diagnóstico grátis na bio.\nfreeme.viviannedossantos.com" },
    ],
    caption: "30 anos de ciência num post: tu nunca foste o problema. O isolamento sim.\n\nMaternal brain, burnout materno, solidão materna — todos têm nome científico e nenhum é falha tua.\n\nGuarda este post. Vai precisar dele.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #CiênciaDaMaternidade #BurnoutMaterno #MaternalBrain #MãeSemCulpa #SaúdeMentalMaterna #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 29,
    type: "video",
    categoria: "ferida",
    title: "A mãe perfeita não existe",
    slides: [
      { layout: "kinetic-line", body: "Ela nunca perde a paciência." },
      { layout: "kinetic-line", body: "Está sempre disponível." },
      { layout: "kinetic-line", body: "Dá conta de tudo, sozinha, a sorrir." },
      { layout: "kinetic-line", body: "Conheces esta mãe?" },
      { layout: "kinetic-line", body: "Ela não existe.", bold: ["não existe"] },
      { layout: "kinetic-line", body: "Nunca existiu." },
      { layout: "kinetic-line", body: "E quanto mais a tentas ser, maior a vergonha de não conseguir." },
      { layout: "kinetic-line", body: "\"Pertenço exactamente como sou.\nFico, mesmo sem ser perfeita.\"" },
      { layout: "kinetic-line", body: "FreeMe. Diagnóstico grátis na bio." },
    ],
    caption: "A mãe perfeita é a maior mentira que te contaram.\n\nE é ela que te faz sentir que falhas todos os dias.\n\nPertenço exactamente como sou.\n\nGuarda e envia a uma mãe que precisa.\n\nDiagnóstico grátis na bio.",
    hashtags: "#FreeMe #MãePerfeita #MãeImperfeita #AVergonha #MaternidadeReal #MãeSemCulpa #Autocompaixão #ATravessiaDaMãe",
    platforms: ["ig", "tiktok"],
  },

  {
    day: 30,
    type: "carousel",
    categoria: "cta",
    title: "30 dias, 7 bloqueios, uma travessia",
    slides: [
      { layout: "capa", body: "30 dias.\n7 bloqueios.\nUma travessia.\n\nO que aprendemos juntas.", bold: ["Uma travessia"] },
      { layout: "conteudo", body: "Aprendeste o que é o PESO:\ncarregar o que não é teu por lealdade.", bold: ["PESO"] },
      { layout: "conteudo", body: "Aprendeste o que é o VAZIO:\ndar mais do que recebes durante anos.", bold: ["VAZIO"] },
      { layout: "conteudo", body: "Aprendeste o que é a CULPA:\nquerer reparar através do sofrimento.", bold: ["CULPA"] },
      { layout: "conteudo", body: "Aprendeste o que é o MEDO:\nvigiar o que viaja entre gerações.", bold: ["MEDO"] },
      { layout: "conteudo", body: "Aprendeste o que é a VERGONHA:\ncomparar-te com uma mãe que não existe.", bold: ["VERGONHA"] },
      { layout: "conteudo", body: "Aprendeste o que é a MÁGOA:\na ferida de filha que sangra quando és mãe.", bold: ["MÁGOA"] },
      { layout: "conteudo", body: "Aprendeste o que é o RANCOR:\na casca dura sobre a ferida.", bold: ["RANCOR"] },
      { layout: "citacao", body: "Agora sabes os nomes. E o que tem nome pode ser tratado.", bold: ["pode ser tratado"] },
      { layout: "cta", body: "Diagnóstico grátis.\n\nfreeme.viviannedossantos.com" },
      { layout: "assinatura", body: "FreeMe\nA Travessia da Mãe\nVivianne dos Santos" },
    ],
    caption: "30 dias depois, sabes os nomes. E o que tem nome pode ser tratado.\n\nO FreeMe é a travessia adaptada a ti. Diagnóstico grátis: freeme.viviannedossantos.com\n\nPartilha com uma mãe que precisa.",
    hashtags: "#FreeMe #ATravessiaDaMãe #7Bloqueios #ConstelacaoFamiliar #CulpaMaterna #MãeSemCulpa #DiagnósticoGrátis #Maternidade",
    platforms: ["ig", "tiktok"],
  },
];
